### ISSUE TITLE
IPN hiba

### ISSUE THREAD

**Issue by nagypal0121** [conedevelopment/simplepay-gateway#100]
- Simplepay Gateway bővítmény verzió: 2.5.3
- WooCommerce verzió: 6.9.2
- WordPress verzió: 6.0.2
- PHP verzió: 8.0.23

Fizetésnél az IPN CONTENTNOTMATCH hibára áll ki.

Úgy sejtem a hibát a WooCommerce Sequential Order Numbers Pro bővítmény okozza ami a rendelésszámot módosítja.

Eredmény CONTENTNOTMATCHSignature NO_SIGNATUREFogadott válasz A rendelés nem található.IPN újrapróbálása xxx Újrapróbálva 2Index 4Időpont 2022.09.25 11:47:31IPN URL https://xxx.hu/?wc-api=wc_gateway_simplepay-gatewayElküldött IPN tartalma {"salt":"vPugrSfbl8Ljnh0vPZbQR988LstOe14v","orderRef":"wc-220925-062414","method":"CARD","merchant":"xxx","finishDate":"2022-09-25T11:37:16+02:00","paymentDate":"2022-09-25T11:35:38+02:00","transactionId":xxx,"status":"FINISHED"}Válasz HTTP kódja 200

**Comment by nagypal0121** [comment]
Megtaláltam a megoldást, a kódban az $order->get_order_number() -t kicsseréltem $order->id -ra. Most tökletesen lefut.

**Comment by iamgergo** [comment]
Szia!

Szándékosan van használva a `$order->get_order_number()`. Elég sok olyan eset merült már fel eddig, ahol ez jobb megoldásnak tűnt mint ha simán az ID-t adjuk át.

A `WooCommerce Sequential Order Numbers Pro` már korábban is okozott problémát, de sajnos nem tudjuk felkészíteni a bővítményt minden eshetőségre.

De köszi, hogy jelezted!
