### ISSUE TITLE
Kupon kedvezmény a Simple oldalán 

### ISSUE THREAD

**Issue by kukac7** [conedevelopment/simplepay-gateway#102]
- Simplepay Gateway bővítmény verzió: 2.5.1 
- WooCommerce verzió: 6.9.4
- WordPress verzió: 6.0.2
- PHP verzió: 7.4.3

hello

a simple oldalan nem latszodik a bevaltott kupon kedvezmenye.
simple emailben sincs, simple adminban sem latszik.

simple admin:
![Screenshot 2022-10-04 at 11 12 09](https://user-images.githubusercontent.com/1240104/193781774-8b64cc49-6089-4ac9-9a65-9a7e7799f3d9.png)

wc admin:
![Screenshot 2022-10-04 at 11 12 38](https://user-images.githubusercontent.com/1240104/193781752-c3d4bb91-aa97-495c-97c7-425df3b063a7.png)

lehet csak en nem alltiok be vmit jol?
koszi a segitseget!

szerk.: mas dolog, hogy most latom, 0% afa-t ir, pedig be van kapcsolva az ado.

**Comment by iamgergo** [comment]
Szia!

Az adókról és a kedvezményekről itt írunk, hogy miért van így: https://simplepay.conedevelopment.com/a-simplepay-bovitmeny-korlatai
