### ISSUE TITLE
Missing mandatory OTP message on thank you page 

### ISSUE THREAD

**Issue by ceo-tukan** [conedevelopment/simplepay-gateway#104]
- Simplepay Gateway bővítmény verzió: 2.5.4
- WooCommerce verzió: 6.9.4
- WordPress verzió: 6.0.2
- PHP verzió: 7.4.32

### Hiba leírása
Hi! The OTP Mobil team is refusing to approve our site as it says the thank you page does not include the following message
 "Sikeres tranzakció.
SimplePay tranzakció azonosító: 500xxxxxx”

Can you let me know what might be missing as I don't see where to configure this, to my understanding the plugin should automatically add it to the thank you page, no?

Thanks,

**Comment by ceo-tukan** [comment]
Thanks Gergo! I tried with the WC default page and had same issue. I tried to switch to twentytwentytwo theme and it shows that row indeed, but "Sikeres tranzakció" mandatory text is missing.
How can I add that row and text, do you know what filter is used to insert it on the thank you page?
Thanks!

**Comment by iamgergo** [comment]
I see. Are you sure it is mandatory? The transaction ID is not enough? This is the first time we hear about that.

**Comment by ceo-tukan** [comment]
I challenged the OTP IT team as well on this. Waiting to hear back, thanks a lot!

**Comment by ceo-tukan** [comment]
Hi Gergo!
So OTP confirmed in the end we could launch like this, thanks!
