### ISSUE TITLE
A rendelések "Fizetésre vár" státuszban ragadnak

### ISSUE THREAD

**Issue by BGERI95** [conedevelopment/simplepay-gateway#105]
- Simplepay Gateway bővítmény verzió: 2.5.4
- WooCommerce verzió: 6.2.2
- WordPress verzió: 6.0.3
- PHP verzió: 8.1 majd visszaváltottam 7.4-re

### Hiba leírása
Jelenleg a SimplePay Sandbox módban vagyok, az éles fiókomat még nem aktiválták, viszont a teszt rendeléseim egytől egyig "Fizetésre vár" státuszban ragadnak.  A `HUF szolgáltató azonosító`, `HUF titkos kulcs` helyes, illetve a Simple fiókba is bemásoltam az `IPN URL`-t, a `Kétlépcsős fizetés` jelölőnégyzet a pluginban nincs bekapcsolva.

A SimplePay fiókban a Tranzakciók alatt ez látható a Communication panelen (az url-t lecseréltem, valójában nem ez a honlap címe):

```
Result NOT200
Signature NO_SIGNATURE
ResponseIndex 1
Finished 2022.10.18 21:28:00
IPN URL https://xyzzzzz.com/?wc-api=wc_gateway_simplepay-gateway
Sent IPN hash {"salt":"LAi3gSwufwe5lrHQ6290zCa1uv4fBvFL","orderRef":"wc-85907",
"method":"CARD","merchant":"OMS53120201","finishDate":"2022-10-18T21:27:59+02:00",
"paymentDate":"2022-10-18T21:27:41+02:00","transactionId":502221300,"status":"FINISHED"}
Response status code 403
```

Ha manuálisan a Send IPN gombra kattintok a SimplePay felületén a Tranzakcióknál, akkor is ugyan ez az eredmény, valamint egy 
`??payment.NOT200_en??` üzenet jelenik meg egy piros értesítési boxban.

Mi okozhatja ezt a problémát és mi lenne a megoldás?

**Comment by BGERI95** [comment]
Meg is oldódott az IPN probléma, az Elin tárhelyszolgáltatónál a következőképpen:

A Tárhely admin felületen a Webtárhely -> Webtárhely menüpontban a PHP.ini -re kattintva bekapcsoltan az `ioncube loader`-t, és a ugyanebben a menüpontban a `bad bot`-ot kikapcsoltam, hogy a Simplepay IPN hívást ne dobja el.

**Comment by iamgergo** [comment]
Szia!

Szuper, köszi a visszajelzést, örülünk, hogy megoldódott!
