### ISSUE TITLE
Changelog update

### ISSUE THREAD

**Issue by jofbe** [conedevelopment/simplepay-gateway#107]
Sziasztok!
A [changelog](https://github.com/conedevelopment/simplepay-gateway/blob/c20030f2ea5ab53611bd50da4047381ac9ee50b0/CHANGELOG.md)-ot tudnátok frissíteni?
Köszi!

**Comment by iamgergo** [comment]
Szia!

Áttértünk ide: https://github.com/conedevelopment/simplepay-gateway/releases
