### ISSUE TITLE
IPN hiba - hibás tartalom a válaszban

### ISSUE THREAD

**Issue by andrasdeak** [conedevelopment/simplepay-gateway#110]
- Simplepay Gateway bővítmény verzió: 2.5.4
- WooCommerce verzió: 7.1.0
- WordPress verzió: 6.1.1
- PHP verzió: 7.4.30

Korábban teljesen jól működött minden, aztán sajnos lefrissült a WP, a WC és kb az összes egyéb plugin. Jelenleg a fizetési folyamat ott akad el, hogy simplepay oldalon kártya adatok megadása után nem autorizál. 
Simplepay hiba leírás:
Eredmény: CONTENTNOTMATCH 
Signature: NO_SIGNATURE 
Fogadott válasz: A rendelés nem található.
HTTP hibakód: 200
Elküldött tartalom (sózást és a merchant ID-t kiszedtem): `{"salt":"XXX","orderRef":"101010516693953013136","method":"CARD","merchant":"XXX","finishDate":"2022-11-25T17:55:34+01:00","paymentDate":"2022-11-25T17:55:01+01:00","transactionId":329900276,"status":"FINISHED"}`

Tudnátok kérlek segíteni, hogy mi lehet a gond? 

A WC amúgy egy Webnus által fejlesztett "Modern Event Calendar Pro" plugintól kapja a termékeket, a WC-t csak kosár + checkout-ra használja ez a megoldás. Eddig ez hibátlanul működött és a frissítéseken kívül semmilyen egyéb plugin nem lett telepítve, az oldalon sem történt módosítás azon kívül, hogy új termékek (események) is hozzáadásra kerültek. (A régiekkel is ugyanez az IPN hiba van). 

Nagyon köszönöm előre is!!

**Comment by andrasdeak** [comment]
Közben ezt sikerült egy teljes WP újrarakással megoldani. ME Calendar Pro + WooCommerce integrációban volt a gond, feltehetően nem a ti pluginetekkel.

**Comment by iamgergo** [comment]
Szia!

Köszi a visszajelzést, örülünk, hogy megoldódott.
Gondolom az order ID-val volt valami kavarodás.
