### ISSUE TITLE
Sikeres fizetes utan az Order statusza "feldolgozas alatt" marad

### ISSUE THREAD

**Issue by sknight80** [conedevelopment/simplepay-gateway#111]
- Simplepay Gateway bővítmény verzió: 2.5.4
- WooCommerce verzió: 7.2.0
- WordPress verzió: 6.1.1
- PHP verzió: 7.3.5

### Hiba leírása
Feltunt nekem, hogy amikor az ugyfelunk a weboldalunkon vasarol voucher-t (virtualis termek) simplepay-en keresztul, a megrendeles statusza "Feldolgozas alatt" -ban marad sikeres fizetes utan es nem valtozik a megrendeles statusza "Teljesitve".  

Ez most a kiegeszito limitacioja vagy nekem kell egy kis kodot berakjak a WP-be, hogy amikor sikeres fizetes megtortent, akkor a status menjen at "Teljesitve" statusba?

Extra info:
```
2022-12-14T15:16:04+00:00 INFO Az IPN hívás megtörtént.
{"salt":"<removed>","orderRef":"wc-15201","method":"CARD","merchant":"<removed>","finishDate":"2022-12-14T16:16:01+01:00","paymentDate":"2022-12-14T16:12:37+01:00","transactionId":33<reducted>,"status":"FINISHED"}
```

**Comment by ghenius30** [comment]
Szia,
Nekem is feltűnt ez a probléma.

Kicsit bele kellett nyúlni a pluginba, az IPNHandler.php-ba írtam egy kis scriptet, ami lekérdezi az aktuális ordert, és átállítja 'completed'-re az order státuszát.

`<?php

namespace Cone\SimplePay\Handlers;

use Cone\SimplePay\Support\Log;

class IPNHandler extends Handler
{
    /**
     * Handle the IPN request.
     *
     * @param  array  $payload
     * @return void
     */
    public function handle($payload)
    {
        Log::info(sprintf(
            "%s\n%s",
            __('IPN event was fired.', 'cone-simplepay'),
            json_encode($payload)
        ));

        $order = wc_get_order( $this->order->get_id() );
        $order->update_status( 'completed' );

        //$this->order->payment_complete();
    }
}`

**Comment by sknight80** [comment]
@ghenius30  a `$this->order->payment_complete();` sor miert van kikommentezve?

**Comment by ghenius30** [comment]
@sknight80 amikor teszteltem akkor az `$order->update_status( 'completed' );` átállította 'completed'-re a státuszt, és a `$this->order->payment_complete();` pedig visszaállította 'processing'-re a státuszt.

**Comment by ghenius30** [comment]
@sknight80 most teszteltem, valóban így is megfelelően működik. :)

**Comment by sknight80** [comment]
@ghenius30 kiraly. Akkor berakom ezt a modositast en is a pluginba.

**Comment by ghenius30** [comment]
@sknight80  csak ne felejtsd el, ha update van, valószínűleg ezt ki fogja törölni belőle, és majd neked kell vissza tenned.

**Comment by iamgergo** [comment]
Sziasztok!

Ha jól értem akkor ez csak virtuális termék esetében probléma?

> csak ne felejtsd el, ha update van, valószínűleg ezt ki fogja törölni belőle, és majd neked kell vissza tenned.

Ha ez valóban megoldás, akkor bevesszük a forráskódba. @ghenius30 @sknight80 Ha esetleg van kedvetek nyitni egy PR-t erre, akkor örömmel vesszük.

Köszi!

**Comment by sknight80** [comment]
Szia @iamgergo ,

Mivel mi csak virtualis termeket arusitunk igy en csak azzal kapcsolatban tudok nyilatkozni.  Es igen ott ez problema.  Ha gondolod szivesen nyitok ezzel kapcsolatban egy PR-t.  

Istvan

**Comment by ghenius30** [comment]
Szia @iamgergo ,
Én is virtuális termékekkel, rendezvények regisztrációs díjával foglalkozom.

**Comment by iamgergo** [comment]
@sknight80 @ghenius30 Volt egy kis időm rá, így nyitottam egy PR-t. Esetleg le tudjátok tesztelni, hogy ez a kód (https://github.com/conedevelopment/simplepay-gateway/pull/112/files#diff-6a50c0e79f358172c2f4624731357a53c4440b1c0f7459c983752400444f47c2R24-R35) működik-e megfelelően?

Köszi!

**Comment by ghenius30** [comment]
@iamgergo teszteltem, nekem így már jól működik virtuális termék esetén.

**Comment by sknight80** [comment]
@iamgergo hagytam egy kérdést a PR ban. Jónak tűnik nekem és működik is. A kérdés majd azokhoz fog menni akik több fajta terméket árusítanak. Virtuális meg fizikai. Ok bútor meg ajandekkartya. Bár az utóbbi lehet mindkettő típusban.

**Comment by iamgergo** [comment]
Kösz az asszitot, mergeltem a PR-t és frissítettem a verziót. Ezt pedig zárom.
