### ISSUE TITLE
PHP 8 kompatibilitás?

### ISSUE THREAD

**Issue by milbar** [conedevelopment/simplepay-gateway#116]
- Simplepay Gateway bővítmény verzió: 2.5.6
- WooCommerce verzió: 7.4.0
- WordPress verzió: 6.1.1
- PHP verzió: 7.4.26

Sziasztok!
Igazából egy kérdésem volna a bővtménnyel kapcsolatban.

A composer-t használok a bővítmények kezelésére feltűnt, hogy a `Simplepay Gateway bővítmény` `conposer.json` fájlban `"php":"^7.2",` van megadva. 
Szeretném frissíteni a projektem php 8.0-ra első körben. Nyilván ez a paraméter miatt a composer jelez.

Kompatibilis a bővítmény **php8.0**-val?
Tesztelte már valaki? 
Megköszönöm a tapasztalataitokat.

Köszönöm,
Milán

**Comment by iamgergo** [comment]
Szia,

Igen, kompatibilis a bővítmény 8-as verzió felett is.
Idő hiányában egy darabig nem tudok foglalkozni vele, de ha gondolod, akkor szívesen veszünk egy PR-t.

Köszi!

**Comment by milbar** [comment]
Köszönöm,
meg is van: 
#117

**Comment by iamgergo** [comment]
Köszi!

**Comment by csiakgyula** [comment]
Sziasztok,

PHP 8.2 esetében a Query Monitor még az alábbiakat jelzi be, mint Warning. Ezekre is kaphatnánk esetleg megoldást egy következő Release-ben? Habár elvileg hibát nem okoz(hat), attól még zavaró tud lenni, hogy a Query Monitor "villog" miatta, mint egyfajta FALSE ALARM :-) ...

Előre is köszönöm!

Query Monitor:
------------------ DUMP START ----------------------
<html>
<body>


Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$prefix is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
-- | -- | -- | -- | --
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$notification_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$sanbox_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$sandbox is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$huf_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$huf_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$huf_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$huf_sandbox_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$huf_sandbox_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$eur_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$eur_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$eur_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$eur_sandbox_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$eur_sandbox_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$usd_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$usd_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$usd_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$usd_sandbox_merchant is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$usd_sandbox_secret_key is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$icon_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$show_icon is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$debug_settings is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116 | Plugin: simplepay-gateway-master
Deprecated | Creation of dynamic property Cone\SimplePay\Gateway::$debug is deprecated | 1 | +wp-content/plugins/simplepay-gateway-master/src/Gateway.php:116


</body>
</html>
------------------ DUMP END ----------------------

**Comment by iamgergo** [comment]
Szia!

Ebben a verzióban már nem tervezünk módosítani a kódon.

A következő, átdolgozott, kibővített (és valószínűleg nem ingyenes) verziónál ezt figyelembe fogjuk venni.

Köszi!
