### ISSUE TITLE
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by gabermeszaros** [conedevelopment/simplepay-gateway#118]
- Simplepay Gateway bővítmény verzió: 2.5.6 verzió
- WooCommerce verzió: 7.4.1 verzió
- WordPress verzió: 6.1.1
- PHP verzió: 8.1

Minden látszólag jól van beállítva a sandbox-ban, a Merchant, Secret Key, IPN, viszont ezt a hibát dobja fel. Az egyetlen eltérés, hogy a szerződött URl a Simple fiókban www. előtagú, míg az oldal enélkül megy. 
A logban az alábbiak vannak:
2023-03-01T15:18:39+00:00 INFO Request is invalid: {"errorCodes":[5302],"salt":"HuRyaI3DO8Zb20x9OKm0sUbyKwgwMheu","total":0.0} - minden egyes tesztnél más-más azonosítóval ugyanez. 

Köszönöm szépen a segítséget!
Gábor

**Comment by iamgergo** [comment]
Szia!

Szerintem ez a különbség a gond. Az 5302-es az signature hiba, azaz nem egyezik a két hash.
Ha az egyik oldalon van www a másikon nincs, akkor hash el fog térni.
