### ISSUE TITLE
Hiba üzenet 

### ISSUE THREAD

**Issue by rakricsi** [conedevelopment/simplepay-gateway#122]
- Simplepay Gateway bővítmény verzió: 2.5.6
- WooCommerce verzió: 7.7.0
- WordPress verzió: 6.2
- PHP verzió: 7.4
www.doatoys.hu

### Hiba leírása

Üdv!

A kérdésem az lenne, hogy telepítettem a bővítményt.
Megvan a simple fiók. 
Megadtam a HUF kiszolgáló azonosító és a HUF Titkos kulcsot.

Engdélyeztem a SimplePayt de a fizetési oldalon:

De a kövektező hiba üzenetet kapom: 
"Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."

Kihagytam egy lépést esetleg? 
Köszönöm a segítséget. 

Üdv 
Rák Richárd

**Comment by iamgergo** [comment]
Üdv,

Ennek rengetek oka lehet, ennyi információ alapján sajnos nem tudunk segíteni.
Lehet, hogy nem kapcsoltad be a sandbox módot?

**Comment by borex** [comment]
Az IPN URL-t beállítottad a SimplePay adminban?
