### ISSUE TITLE
Magyar webshopban angol hibaüzenetek

### ISSUE THREAD

**Issue by Fjancsi-CAD** [conedevelopment/simplepay-gateway#123]
- Simplepay Gateway bővítmény verzió: 2.5.6
- WooCommerce verzió: 7.7.2
- WordPress verzió: 6.2.2
- PHP verzió: 7.4.33

### Hiba leírása

Sziasztok!

Igazából minden jól működik, csak a hibaüzenetek mintpéldául, ha megszaktom a fizetést angolul rja a szöveget, pedig a webshop nyelve magyar. A Simple admin ezt ki is szúrta. nemtudom mi lehet a probléma.

Üdv,
Jani.

![Képernyőkép 2023-06-06 212731](https://github.com/conedevelopment/simplepay-gateway/assets/57772717/170f9763-ecd5-4cae-8f99-1eee7b6a6429)

**Comment by borex** [comment]
A po fájlból hiányzik a következő:
#: src/Handlers/PaymentHandler.php:36
msgid "You cancelled your transaction: %d."
msgstr "Megszakított tranzakció. Tranzakció azonosító: %d."

**Comment by Fjancsi-CAD** [comment]
Szia. Pontosan melyik PO-ba kell belerakni? OTP SimplePay Gateway for WooCommerce vagy simán csak a Woocomerce PO-jába?

**Comment by borex** [comment]
Szia. A languages/cone-simplepay-hu_HU.po fájlba:

`#: src/Handlers/PaymentHandler.php:36
msgid "You cancelled your transaction."
msgstr "Megszakított tranzakció."

**#: src/Handlers/PaymentHandler.php:36
msgid "You cancelled your transaction: %d."
msgstr "Megszakított tranzakció. Tranzakció azonosító: %d."**
`

**Comment by Fjancsi-CAD** [comment]
Szia. Köszönöm a segtséget, mostmár működik. Csak annyi volt még, hogy a MO. fájlt is át kellett írni.

**Comment by borex** [comment]
Szívesen. Én azt szoktam csinálni, hogy a loco translate-el megnyitom módosításra a fájlt és beírok egy hézagot, mentem, majd kitörlöm a beírt karakter és újra mentek. Így újra generálódik az mo fájl. Más megoldás POEditor használata.

**Comment by iamgergo** [comment]
@borex Köszi szépen!
