### ISSUE TITLE
IPN hiba

### ISSUE THREAD

**Issue by Slewy84** [conedevelopment/simplepay-gateway#124]
- Simplepay Gateway bővítmény verzió: #.#.#
- WooCommerce verzió: #.#.#
- WordPress verzió: #
- PHP verzió: #.#.#

### Hiba leírása

Ezúton tájékoztatjuk, hogy a(z) [https://www.hajoagyu.hu](https://www.hajoagyu.hu/?fbclid=IwAR3pLG0g_1Wg3QdcLntHPthGqog17lCKsnyTJSSBwn3EitIgqAP5Zqds4yA) weboldalán indított az alábbiakban részletezett rendelést a vásárló sikeresen rendezte. Mindazonáltal az Ön rendszerének kiküldött IPN üzenet többszöri próbálkozás után sem lett sikeresen visszaigazolva. Kérjük ellenőrizze az IPN beállításokat.

Ezt a hibaüzenetet kaptuk.

**Comment by iamgergo** [comment]
Üdv,

Ezzel nem sokat tudunk kezdeni ebben a formában.

- az IPN URL be lett állítva?
- ha igen, akkor milyen választ ad?
- elképzelhető, hogy egy tűzfal bővítmény blokkolja a hívást?

Ezekben az oldal fejlesztője biztosan tud segíteni.

**Comment by konyves** [comment]
Sziasztok tegnap óta nekem is ez a hiba jön fel.
Egy új bővítményt raktam fel, de ezt kikapcsoltam, nehogy ez legyen a gond.
De ugyan az a hiba :(
IPN url beállítva évek óta jól megy, tűzfal nem változott.

**Comment by iamgergo** [comment]
Üdv,

Nálunk továbbra sem volt változás, tehát mi nem nagyon tudunk segíteni.

A SimplePay felé jelezzétek a hibát, hátha ők többet tudnak mondani.
