### ISSUE TITLE
Woocommerce HPOS kompatibilitás

### ISSUE THREAD

**Issue by Maroo004** [conedevelopment/simplepay-gateway#126]
Sziasztok!

- Simplepay Gateway bővítmény verzió: 2.5.7
- WooCommerce verzió: 8.0.1
- WordPress verzió: 6.3
- PHP verzió: #.#.#

### Hiba leírása

Érdeklődöm, hogy tervezitek-e a bővítmény frissítését, hogy támogassa a woocommerce HPOS-t?

**Comment by iamgergo** [comment]
Hello,

Ebben az ingyenes verzióban már nem tervezünk ilyen bővítést.

**Comment by szepeviktor** [comment]
@iamgergo Egy sor lenne
https://github.com/Barn2Media/woo-custom-add-to-cart-button/compare/1.2.1...1.2.2#diff-c346b1aeac8259782c74702eadfe1d7a240ee3ecea6020ad2addede93c635cab
Sajnos nem értem, "mit kapcsol be".

**Comment by iamgergo** [comment]
A dokumentáció alapján az lenne a lényeg, hogy a rendelésekkel a megfelelő függvényeken keresztül interaktáljunk. Ehhez át kell nézni a kódot és migrálni ahol kell.
