### ISSUE TITLE
Hiba a fizetés feldolgozásakor.

### ISSUE THREAD

**Issue by Indoraptor1** [conedevelopment/simplepay-gateway#129]
- Simplepay Gateway bővítmény verzió: 2.5.7
- WooCommerce verzió: 8.0.3
- WordPress verzió: 6.3.1
- PHP verzió: 8.1

### Hiba leírása
Nem lehet fizetni SimplePay-el, mert mmindig ezt a hibát dobja ki:
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

A log file-t merre találom?

**Comment by attilakobza** [comment]
uploads/wc-logs/simplepay-gateway-xxxxxxx.log

Én is ezt debugolom most

**Comment by Indoraptor1** [comment]
Nekem élesben sem működik :(

**Comment by attilakobza** [comment]
Élesben nem is fog amíg nem veszik át, a sandbox-ot próbáld.

**Comment by Indoraptor1** [comment]
Eddig tökéletesen működött

**Comment by iamgergo** [comment]
Hello,

A kódon nem változtattunk, így nem valószínű, hogy itt a gond. 
Érdemes lehet a Simple-től megkérdezni, hogy mi a helyzet, lehet, hogy ők többet tudnak mondani.
