### ISSUE TITLE
Nem felel meg a bővítmény működése a dokumentációban leírtaknak

### ISSUE THREAD

**Issue by zbacsi** [conedevelopment/simplepay-gateway#130]
- Simplepay Gateway bővítmény verzió: 2.5.7
- WooCommerce verzió: 7.9
- WordPress verzió: 6.2.2.
- PHP verzió: 8.1

### Leírás

Sikertelen fizetés után a visszatérő oldalon a fejlesztési dokumentációban meghatározott szövegezést kellene használni, ami a következő:
Sikertelen tranzakció.
SimplePay tranzakció azonosító: 5xxxxxxxx
Kérjük, ellenőrizze a tranzakció során megadott adatok helyességét. Amennyiben minden adatot helyesen adott meg, a visszautasítás okának kivizsgálása kapcsán kérjük, szíveskedjen kapcsolatba lépni kártyakibocsátó bankjával.

Megszakított fizetés után (amikor a vásárló a SimplePay fizető oldalon megnyomja a "vissza a kereskedő oldalára" gombot), hiányzik a vásárló szöveges tájékoztatása: "Megszakított fizetés!"

Sikeres tranzakció után a visszatérő oldalon hiányzik a SimplePay tranzakció azonosító: 5xxxxxxxx

Mindhárom esetben jelenleg a pénztár oldalra irányít vissza az oldal. 

### Reprodukáláshoz szükséges lépések

Teszteld a fenti eseteket és láthatod, hogy nem írja ki a szükséges szövegeket, adatokat, csak simán visszadob a kosárhoz.

A korábbi hibajelentésemre az volt a válasz, hogy ebben az ingyenes verzióban ezt már nem javítjátok. Ha ez egy megszüntetésre szánt plugin, akkor miért nem írjátok ki a readmeben egyértelműen, hogy ne használjuk, ne építsünk rá, hanem keressünk egy fizetőset?

**Comment by iamgergo** [comment]
> Teszteld a fenti eseteket és láthatod, hogy nem írja ki a szükséges szövegeket, adatokat, csak simán visszadob a kosárhoz.

Nekem mind három esetben a megfelelő működés lép fel a teszt során.

> A korábbi hibajelentésemre az volt a válasz, hogy ebben az ingyenes verzióban ezt már nem javítjátok. 

Ez egy Open Source bővítmény. Ha úgy érzed, hogy van olyan megoldásod a fenti problémára ami biztosan mást nem tör meg, akkor szeretettel várjuk a PR-t.

> Ha ez egy megszüntetésre szánt plugin, akkor miért nem írjátok ki a readmeben egyértelműen, hogy ne használjuk, ne építsünk rá, hanem keressünk egy fizetőset?

Majd ha jónak látjuk ezt kiírjuk. Ha úgy érzed, hogy egy ingyenes, MIT license alatt futó megoldás nem tud annyit amit szeretnétek, tudok javasolni pár alternatívát:

- https://github.com/new (ha írnál egy újat)
- https://wps.hu/wordpress-woocommerce-simplepay-bovitmeny/
- https://bitron.hu/simplepay-for-woocommerce/
- https://woocommerce-shop.hu/simplepay
- https://wpszaki.hu/simplepay-kiegeszito-woocommerce-hez/
- https://hellowp.io/hu/t/woocommerce-bankkartyas-fizetes-telepites/

**Comment by zbacsi** [comment]
A hiba oka még mindig az inkompabilitás a WooCommerce Sequential Order Numbers Pro pluginnal és kikapcsolhatatlan prefix. A wc_get_order nem fogja megtalálni a rendelést a fenti plugin által generált azonosítóval és az erőszakosan eléragasztott wc- prefixxel. 

A megoldásom közöltem múltkor is, arra kaptam azt a választ, hogy ez ebben az ingyenes verzióban már nem lesz javítva. Pedig semmit nem árt, csak egy plusz lehetőség, ha nincs meg a rendelés. Mutatom újra:

if (! $order instanceof WC_Order) {
            // search for the order by custom order number
             $query_args = array(
                 'numberposts' => 1,
                 'meta_key'    => '_order_number_formatted',
                 'meta_value'  => preg_replace("/^wc-/","", $payload['o']),
                 'post_type'   => 'shop_order',
                 'post_status' => 'any',
                 'fields'      => 'ids',
             );
     
             $posts            = get_posts( $query_args );
             list( $order_id ) = ! empty( $posts ) ? $posts : null;            
             // order was found
             if ( $order_id !== null ) {
                 $order=wc_get_order($order_id);
             }
       }

Át fogom nézni a kódot, hogy hány helyen van még ilyen rendelés beazonosítási probléma és menni fog a PR, ahogy időm engedi.
