### ISSUE TITLE
megszűnt a korábban hibátlanul működő Product Bundles by WooCommerce plugin kompatibilitás :(

### ISSUE THREAD

**Issue by ucsendre** [conedevelopment/simplepay-gateway#134]
- Simplepay Gateway bővítmény verzió: 2.6.1
- WooCommerce verzió: 8.1.0
- WordPress verzió: 6.3.1
- PHP verzió: 8.2.10

### Leírás
A Simplepay Gateway 2.6.0 verziója óta kompatibilitási hiba miatt nem lehet bankkártyával kifizetni a Product Bundles by WooCommerce (https://woocommerce.com/products/product-bundles/) pluginnal összeállított csomag termékeket. 
A 2.6.1 verzióval is maradt ez a hiba.
A korábbi (2.5.7) verzióval minden hibátlanul működik.
Részünkről ez megoldja a gondot, de így bukjuk a frissítéseket, ami hosszabb távon nem egészséges.

### Reprodukáláshoz szükséges lépések
Sajnos szükséges hozzá a fizetős Product Bundles by WooCommerce (https://woocommerce.com/products/product-bundles/) plugin.
:(

**Comment by iamgergo** [comment]
Gondolom ez összefügghet ezzel #133.

**Comment by iamgergo** [comment]
@ucsendre Meg tudod nézni kérlek, hogy ezzel a committal megy, e? https://github.com/conedevelopment/simplepay-gateway/tree/5647b71a7372868543770311c9d283b3995d61e1 (csak le kell tölteni a zipet)

**Comment by ucsendre** [comment]
> @ucsendre Meg tudod nézni kérlek, hogy ezzel a committal megy, e? https://github.com/conedevelopment/simplepay-gateway/tree/5647b71a7372868543770311c9d283b3995d61e1 (csak le kell tölteni a zipet)

Sajnos nem működik.

Frontend:
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

Szerver (nginx) error log:
[error] 761254#0: *653581 access forbidden by rule, client: 162.158.111.137, server: noirot.hu, request: "POST /xmlrpc.php HTTP/2.0", host: "noirot.hu"

**Comment by iamgergo** [comment]
@ucsendre Köszi! Nem hiszem az nginx log ezzel lenne összefüggésben.

Kb sikerült beazonosítani (azt hiszem). Commitolok egyet és jelzek.

Köszi!

**Comment by iamgergo** [comment]
@ucsendre Kiment egy új release. Meg tudod erősíteni, hogy a v2.6.2-es verzióval rendben működik? Köszi!

**Comment by ucsendre** [comment]
@iamgergo 
Szia! Igen, ez jónak tűnik. Működnek a csomagok is.
Köszönöm a gyors segítséget!
:)

**Comment by iamgergo** [comment]
@ucsendre Kiderült, hogy van egy olyan eset, amikor a mostani verzió nem működik bizonyos kupon variációk esetén. Ellenben a korábbi módosítás ami a kuponokkal működött, az pedig nektek nem volt jó.

Most módosítottam egyet a kódon. Ha lesz lehetőséged/kapacitásod rá, meg tudod nézni, hogy a mostani legfrissebb commit-tal nektek is rendben működik-e? Nem akarok releaselni csak úgy, nehogy törjön valahol.

Nagyon köszi!

**Comment by ucsendre** [comment]
@iamgergo Sajnos "hiba a fizetés feldolgozásakor" üzenettel megáll és nem továbbít a simplepay oldalára.
Köszönöm, hogy figyeltél ránk.

**Comment by iamgergo** [comment]
@ucsendre Köszönöm!

Azt hiszem, most kikerült az a frissítés ami mind a két esetet lekezeli.
Remélhetőleg utoljára, kérhetek még egy megerősítést, hogy a legfrissebb kóddal, most rendben működik nektek?

Ha igen, akkor kiadom az új verziót.

Köszi szépen!

**Comment by ucsendre** [comment]
@iamgergo Ezzel a verzióval továbbjutok a simplepay fizetési oldalra.
A simplepay admin felületén megjelennek a tranzakció adatai (ügyfél adatok, termékek) és az összeg is stimmel.
Egy tranzakcióban 2 különböző bundle termékkel teszteltem.
Így 99,99% valószínűséggel jó lesz nekünk is.
Köszönöm!

**Comment by iamgergo** [comment]
@ucsendre Szuper vagy, köszönöm a segítséget!
