### ISSUE TITLE
Nem tudnak fizetni az vásárlóim SimplePayel, ha ajándék van beállítva: Free Gifts for WooCommerce

### ISSUE THREAD

**Issue by Fjancsi-CAD** [conedevelopment/simplepay-gateway#135]
- Simplepay Gateway bővítmény verzió: 2.6.1
- WooCommerce verzió: 8.1.1
- WordPress verzió: 6.3.1
- PHP verzió: 7.4.33

Gyanús volt, hogy vásárlóim nem fizetnek SimplePay-en keresztül, valamint kaptam egy e-mailt is a hibáról és reprodukáltam is. Azután feljöttem GitHub-ra  és láttam más ilyen bundle kombó pluginnal is baj van. Kikapcsoltam az ajándék hozzáadását Free Gifts for WooCommerce addonsban. Csináltam teszt vásárlás és müködik a Simplepay! Természetesen a Free Gifts for WooCommerce-is elő vagyok fizetve HelloWP-n keresztül. 

A mai napon 3 vásárlót vesztettünk ezért. Továbbá a hirdetéseimben is szerepel az ajándék a csomagban, ezért nagyon hálás lennék a javításért.

Üdv,
János

**Comment by iamgergo** [comment]
@Fjancsi-CAD Most kiment egy frissítés. Meg tudod erősíteni, hogy a a frissítéssel rendben működik? Köszi!

**Comment by Fjancsi-CAD** [comment]
Működik! Köszönöm szépen a gyors segtséget!!!
