### ISSUE TITLE
Nem működik a fizetés

### ISSUE THREAD

**Issue by Indoraptor1** [conedevelopment/simplepay-gateway#139]
- Simplepay Gateway bővítmény verzió: 2,7,0
- WooCommerce verzió: 8.1.1
- WordPress verzió: 6.3.1
- PHP verzió: 8.1.15

### Hiba leírása
Nem működik a plugin, mindig fizetési hibát dom vissza.

Amikor megnyitom a /?wc-api=wc_gateway_simplepay-gateway oldalt ezt a hibaüzenetet kapom:

 Fatal error: Uncaught Error: hash_equals(): Argument #1 ($known_string) must be of type string, null given
in /var/www/mydomain/wp-content/plugins/simplepay-gateway-master/src/Support/Hash.php on line 29

Call stack:

hash_equals()
wp-content/plugins/simplepay-gateway-master/src/Support/Hash.php:29
Cone\S\S\Hash::check()
wp-content/plugins/simplepay-gateway-master/src/Gateway.php:237
Cone\SimplePay\Gateway::handleNotification()
wp-includes/class-wp-hook.php:310
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:334
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-content/plugins/woocommerce/includes/class-wc-api.php:161
WC_API::handle_api_requests()
wp-includes/class-wp-hook.php:310
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:334
WP_Hook::do_action()
wp-includes/plugin.php:565
do_action_ref_array()
wp-includes/class-wp.php:398
WP::parse_request()
wp-includes/class-wp.php:779
WP::main()
wp-includes/functions.php:1335
wp()
wp-blog-header.php:16
require()
index.php:17

**Comment by iamgergo** [comment]
Szerintem ez valamilyen szerverbeállítás lehet nálatok, a $_SERVER['HTTP_SIGNATURE'] üres, nincs értéke.

**Comment by iamgergo** [comment]
@Indoraptor1 Várj, most esik le.

> Amikor megnyitom a /?wc-api=wc_gateway_simplepay-gateway oldalt ezt a hibaüzenetet kapom...

Ezt nem neked kell megnyitni, hanem a SimplePay küld erre IPN értesítést, a megfelelő aláírással.
