### ISSUE TITLE
Fizetési státuszok módosítása

### ISSUE THREAD

**Issue by Yulcsa** [conedevelopment/simplepay-gateway#142]
- Simplepay Gateway bővítmény verzió: 2.7.1
- WordPress verzió: 6.3.2
- PHP verzió: 7.4

### Hiba leírása

Sziasztok!
Egy másik SimplePay-es bővítményt használtunk, de sajnos nem jutottunk dűlőre azügyben, hogy WooCommerce Email customiser pluginnal (többet is próbáltunk) sikeresen tudjuk szerkeszteni a kimenő emailek formáját. Az a bővítmény Custom statusokat hozott létre: Sikeres fizetés, Elakadt fizetés, Sikertelen fizetés stb. Ezeket a státuszokat pedig sajnos nem minden email-sablon módosító plugin látta és tudta kezelni.
Letöltöttem, teszteltem a Ti verziótokat: nem virtuális termék esetén sikeres fizetés után rögtön Processing, majd Completed státuszt kapott a rendelés.
Van valamilyen módja annak, hogy ne kerüljön Completed státuszba rögtön? Nekünk idő, míg a rendelés beérkezését követően elkészítjük és kiszállítjuk a termékeket és így félrevezető a megoldás.

Szóval a kérdésem alapvetően arra vonatkozna, hogy kódolás nélkül be tudjuk-e állítani valahol, hogy sikeres és sikertelen fizetés esetén milyen státuszba kerüljön egy-egy rendelés?
Sajnos a kódokhoz nem értek, nincs hozzá segítség.

Köszönet előre is a válaszért, segítségért!

**Comment by iamgergo** [comment]
Szia!

> nem virtuális termék esetén sikeres fizetés után rögtön Processing, majd Completed státuszt kapott a rendelés

Mi csak abban az esetben állítjuk completedre, ha a rendelés **minden** terméke virtuális termék.

Nem kaptunk ilyen hibajelentést még korábban. Nem lehet, hogy valamelyik bővítmény kavar be?

**Comment by Yulcsa** [comment]
Kedves Gergő!
Köszönöm szépen a szupergyprs választ! Ellenőriztem, tettem még egy próbát és már szerencsére jól működött. Nem tudom, elsőre mi lehetett a gond - de talán csak egyszeri volt.

Még egy kérdésem lenne - bocsánat, ha nem jó helyen (topikban) teszem fel. (Jelezd kérlek és módosítom.)
Teszteléskor, sikertelen tranzakciónál a weboldalon nem jelenik meg a Sikertelen tranzakciós "blokk". A sikeresnél minden rendben (Rendelés dátuma, száma stb.) De sikertelen (3. kártyaszám) semmi jelzés, csak az újrafizetési opciót látom.
Ebben tudnál kérlek segíteni, hogy ez miért lehet?
Nagyon köszönöm!

**Comment by iamgergo** [comment]
Ha a sikertelen fizetésnél nem jelenik meg a tranzakció azonosító egy üzenetben, akkor érdemes szerintem a téma szintjén keresni, hogy mi a gond. Könnyen lehet, hogy ott felül van írva valami, ami az "admin notice"-okat kezeli.

> Illetve update: az így létrejött rendelés (sikeretelen kártyával) backenden pár percig "Failed", majd:

Szerintem ez ugyan az a gond, amit legelőször említettél. Azt gondolom, ezt nem e bővítményünk csinálja, hanem valami más. Érdemes végigmenni, hogy milyen bővítmények vannak telepítve és azok pontosan mit is csinálnak a rendeléssel egy-egy esetben.

**Comment by Yulcsa** [comment]
Köszönöm szépen a gyprs választ!
Elég lecsupaszított oldalnál próbálkozom: csak a Woo + a Ti pluginotok aktív. Azért is vagyok bajban. Eddig egy másik Simple-plugint használtunk (ott más a gond, amiért váltanánk), de ott ez a rész rendben volt (ugyanezekkel a tesztelési adatokkal).
DIVI-t használunk: kikapcsolatam az egyedi template-et a Cart és a Checkout oldalakra is. Újrapbóálkoztam - sajnos nem javult meg a helyzet. Kikapcsoltam a Shipping plugint is, hátha.
Vártam 10 percet, most még "Failed" mindegyik.
Nem szeretnélek Benneteket itt zavarni és terhelni, ha esetleg mondasz rá egy ajánlatot, hogy beállítsuk az oldalon (először tesztelem ezen a lecsupaszítotton, utána telepíteném az éles webshopba), azt megköszönném!

**Comment by Yulcsa** [comment]
Nagyon hálás lennék egy válaszért ezzel kapcsolatban - hogy kihez fordulhatok, hogy működik, ha szeretnélek megkérni Bennetektet/Téged, hogy állítsuk be/finomítsuk a plugint nálunk. Köszönöm! :)

**Comment by iamgergo** [comment]
@Yulcsa Kérlek vedd fel velünk a kapcsolatot itt: hello@conedevelopment.com

Köszi!

**Comment by Yulcsa** [comment]
Köszönöm, így lesz! :)
