### ISSUE TITLE
WC_Order_Item_Fee error

### ISSUE THREAD

**Issue by tlof** [conedevelopment/simplepay-gateway#143]
[Sun Nov 12 12:46:44.578770 2023] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order_Item_Fee::get_subtotal() in 
/home/users/domain/www/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php:137\nStack trace:
#0 [internal function]: Cone\\SimplePay\\Payloads\\PaymentPayload::Cone\\SimplePay\\Payloads\\{closure}()
#1 /home/users/domain/www/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(142): array_reduce()
#2 /home/users/domain/www/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(53): Cone\\SimplePay\\Payloads\\PaymentPayload::items()
#3 /home/users/domain/www/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(25): Cone\\SimplePay\\Payloads\\PaymentPayload::serialize()
#4 /home/users/domain/www/wp-content/plugins/simplepay-gateway-master/src/Gateway.php(171): Cone\\SimplePay\\Payloads\\PaymentPayload::handle()
#5 /home/users/domain/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): Co...', referer: https://domain.hu/penztar/

Ilyen hiba üzenetekkel van tele az oldal a fizetési folyamatoknál. Néha sikerül néha nem.

Verziók:
PHP 7.4.33
WP: 6.4.1
Woo: 8.2.2
Plugin: 2.7.1
Téma: Uncode
Extra pluginek:
 - redis
 - hucommerce
Fizetési pluginek közül csak a simplepay és a gyári Paypal aktiv.

 
A hiba 11.07-el jött elő.

**Comment by iamgergo** [comment]
https://github.com/conedevelopment/simplepay-gateway/pull/141

**Comment by szepeviktor** [comment]
@iamgergo Fent a stacktrace-t körbe rakod backtick-ekkel, hogy ne linkelje a sok-sok issue-t?

**Comment by tlof** [comment]
Javítva, és elnézést.

**Comment by iamgergo** [comment]
@tlof Javítva a 2.7.2-es verzióban. Köszi, hogy jelezted.
