### ISSUE TITLE
Fizetésre vár státusz

### ISSUE THREAD

**Issue by lokosjoe** [conedevelopment/simplepay-gateway#144]
- Simplepay Gateway bővítmény verzió: 2.7.2
- WooCommerce verzió: 8.3.0
- WordPress verzió: 6.4.1
- PHP verzió: 7.4

### Hiba leírása

Sziasztok!

A bővitény telepítése és beállítása után a rendelések mindig "fizetésre vár" státuszba kerülnek. A visszaigazolás sikeresen megérkezik emailben a simple paytől, illetve a simple pay adminban is sikeres rendelésnek van elkönyvelve. Egyelőre sansbox módot használok, fejlesztés alatt van az oldal.

A termék virtuális termék és jó lenne ha egyből "teljesítve" lenne a státusz miután a fizetés megtörtént és a user vissza lett irányítva a ty page-re.

Lehet gond a plugin beállításaival?

**Comment by iamgergo** [comment]
> A termék virtuális termék és jó lenne ha egyből "teljesítve" lenne a státusz miután a fizetés megtörtént és a user vissza lett irányítva a ty page-re.

Az IPN-t mindenképpen meg kell várni, ami akár 15-30mp-el később is érkezhet mint ahogy át lett irányítva a thank you page-re.

Ha a rendelésben csak virtuális termékek vannak, akkor az IPN-t követően először payment complete majd completed státuszba kerül. Így csak arra tudok gondolni, hogy az IPN nem érkezik meg valamiért. Az IPN URL megfelelően be van állítva a SimplePay adminon?
