### ISSUE TITLE
Következő rendeléshez rendelt Simple azonosító

### ISSUE THREAD

**Issue by gulyaskrisztian** [conedevelopment/simplepay-gateway#153]
- Simplepay Gateway bővítmény verzió: 2.8.0
- WooCommerce verzió: 8.3.1
- WordPress verzió: 6.4.1
- PHP verzió: 8.0.19

Üdv!
A bővítmény szuperül teszi a dolgát, azonban most már másodszor futottunk bele az alábbi hibába:
1-2 percen belül ad le rendelést két különböző vásárló. 

-Az első vásárló Simple-vel fizet, a fizetés szépen végigmegy, az ő oldaláról, illetve a Simple oldaláról is.
-Közben a másik vásárló lead egy rendelést személyes átvétellel és fizetéssel.
-Valamiért az IPN hívás után ennek a második vásárlónak a rendeléséhez rendeli hozzá a Simple azonosítót. A fizetési mód, összegek, stb. mindenhol rendben vannak, viszont a Woo úgy érzékeli, hogy az eredeti rendelés nem ment végbe.

**Comment by ucsendre** [comment]
cache-ben ki van zárva a woocommerce?

**Comment by gulyaskrisztian** [comment]
> cache-ben ki van zárva a woocommerce?
Most már igen. :)

**Comment by iamgergo** [comment]
@gulyaskrisztian Hogy látod, a cache volt a gond?

**Comment by gulyaskrisztian** [comment]
Ma megint előjött a hiba, megint 1 percen belül leadott 2 rendelésnél. 
Az első rendelés volt a SimplePay-es. A Log szerint rendben elment az IPN hívás, stimmel a rendelésszám is, de valamiért megint a másik vásárláshoz rendelte a Simple azonosítót. 

WPRocket-et használunk az oldalon. 

A múltkor mindenhova beletettem exclude-ba a WooCommerce-et,plusz a Simple plugint is. 
A WPRocket  a Woo végpontokat (kosár,pénztár,stb) automatikusan kizárja a gyorsítótárazásból.

Mivel a hibáról más nem ír, biztos, hogy valami nálunk nem kerek... :)

Most kikapcsolom a WPRocket-et ideiglenesen, és meglátjuk.

**Comment by gulyaskrisztian** [comment]
Még annyi, hogy most kiváncsiságból csináltam egy tesztet:
1. Kikapcsoltam a WPRocket-et
2. Inkognitólapról elindítottam egy online fizetéses megrendelést. Rányomtam a megrendelésre.
3. Ezután  a kollegám másik gépről inkognitóból elindított egy utánvétes fizetést.
4. Végigment minden, és így is övéhez rendelte a Simple azonosítót.

**Comment by iamgergo** [comment]
Hosszas mérlegelés után arra jutottunk, hogy ezt ebben a verzióban már nem módosítjuk, potenciálisan nagy a breaking change esélye.

A következő verzióban egyszerűen a rendelés egyedi kulcsát fogjuk használni, így ilyen probléma nem lesz a jövőben. Az adminról kikerül a prefix lehetősége, és egy filterrel lehet majd felülírni a default értéket annak aki akarja.

Azért csináljuk így, mert igyekszünk a lehető legjobban elizolálni a bővítmény működését pl a WCSONP-tól, mert sajnos a hibák egy nagyon nagy részét ennek a bővítménynek a használata okozza.

Köszi az infókat és a közreműködést!
