### ISSUE TITLE
Két különböző merchant egy weboldalon

### ISSUE THREAD

**Issue by neymue** [conedevelopment/simplepay-gateway#158]
Üdv,

Nagyon hasznos ez a plugin a SimplePay egyszerű integrációjához, az lenne a kérdésem, hogy van-e lehetőség ezzel a pluginnal két különböző SimplePay accountot használni egy wordpressen belül? Két külön merchant id, külön számlázás (számlázz.hu pluginhoz hozzá lehet adni több accountot), például termék kategória alapján vagy hasonló megkülönböztetéssel?

**Comment by iamgergo** [comment]
Szia!

Ezt sajnos nem lehet és nem is tervezzük ennek a támogatását (ebben a verzióban biztosan).
