### ISSUE TITLE
SimplePay logó

### ISSUE THREAD

**Issue by Nieder-hu** [conedevelopment/simplepay-gateway#160]
Sziasztok,

most akartuk aktiválni a rendszert az egyik ügyfelünkkel és az a visszajelzés jött a Simple-től, hogy olyan logót kell kitenni a checkoutra, ahol az elfogadott kártyák is látszanak. http://simplepartner.hu/download.php?target=logo

Én most átírom magamnak, de ez biztos egy felmerülő kérdés lesz a jövőben.

Köszi ezúton is!

**Comment by iamgergo** [comment]
Szia!

Mi úgy tudjuk, hogy nem feltétlen a checkouton, hanem az oldalon valahol kell ezt elhelyezni. Erre a plugin egy widgetet tartalmaz, amit a kívánt helyre el lehet helyezni.

A widget a kártyákat is tartalmazza.

**Comment by Nieder-hu** [comment]
Igazad van, nem bontották ki a választ, csak ennyit írtak:

> A SimplePay logók közül legyenek kedvesek a weboldal által elfogadott kártyatársaságok logóival ellátott emblémát választani. A logókat innen tölthetik le: http://simplepartner.hu/download.php?target=logo
