### ISSUE TITLE
Sikeres fizetés a Simplepay szerint, de a WC-ben Pending Payment marad

### ISSUE THREAD

**Issue by Estalhun** [conedevelopment/simplepay-gateway#162]
- Simplepay Gateway bővítmény verzió: 2.8.2
- WooCommerce verzió: 8.5.1
- WordPress verzió: 6.4.2
- PHP verzió: 8.1.18

### Leírás

WC 8.3.1, 8.4.0 és 8.5.1 ugyanaz a hiba

IPN üzenetek
A válaszkód http kódja nem 200, Lezárás 2024.01.18 14:28:57
Eredmény NOT200
Signature NO_SIGNATURE
Fogadott válasz
Index 2
Időpont 2024.01.18 14:28:57
IPN URL https://xxxxx.hu/?wc-api=wc_gateway_simplepay-gateway
Elküldött IPN tartalma {"salt":"iq6O78Ro2JpkiluybAkmnGUye1JZS6Wh","orderRef":"GLM-125581","method":"CARD","merchant":"XXXXX","finishDate":"2024-01-18T14:28:55+01:00","paymentDate":"2024-01-18T14:28:35+01:00","transactionId":503233722,"status":"FINISHED"}

WC 8.3.1:
Válasz HTTP kódja 403

WC 8.4.0 és 8.5.1:
Válasz HTTP kódja 415

### Reprodukáláshoz szükséges lépések
Simplepay fizetés sandbox-ban.

#Forráskód hiba:
Szerintem a Gateway.php hibás a 239-es sorban, mert a $_SERVER globális változónak nincs HTTP_SIGNATURE eleme csak SERVER_SIGNATURE. Hogy köze van-e a hibához, arról fogalmam sincs.

```php
if (! Hash::check($_SERVER['HTTP_SIGNATURE'], $input)) {
    die(__('Invalid signature.', 'cone-simplepay'));
}
```

### WordPress Environment ###
WC Version: 8.5.1
REST API Version: ✔ 8.5.1
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: hu_HU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.1.18
PHP Post Max Size: 1 GB
PHP Time Limit: 1200
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.5.19-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.1

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
astra_adv_header: 6
astra-advanced-hook: 29
attachment: 1236
bsf-sidebar: 12
cartflows_flow: 1
cartflows_step: 2
custom_css: 2
elementor_library: 130
is_search_form: 2
language_switcher: 6
nav_menu_item: 210
oembed_cache: 338
page: 99
pi_dpmw_rules: 2
popup: 2
popup_theme: 8
post: 543
product: 44
pt_view: 1
revision: 164
rp4wp_link: 1602
sa_slider: 2
seopress_404: 3004
seopress_schemas: 1
shop_coupon: 136
shop_order: 4943
shop_order_refund: 2
shopmagic_automation: 1
testimonials: 3
warmcache: 47
wc_afrsm: 2
wc_dynamic_pricing: 13
woo_coupon_reminder: 2
woo_mb_template: 23
wp_global_styles: 1
wp_navigation: 1
wp_show_posts: 1
wp_template: 2
wpforms: 1
ywrac_cart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

OTP SimplePay Gateway for WooCommerce: by Cone Development – 2.8.2
WooCommerce: by Automattic – 8.5.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wooco (wooco)
woosg (woosg)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #9538 - /shop/
Basket: #33 - /cart/
Checkout: #9493 - /checkout/
My account: #35 - /my-account/
Terms and conditions: #1985 - /aszf/

### Theme ###

Name: Twenty Twenty-Four
Version: 1.0
Author URL: https://en-gb.wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-01-20 07:41:34 +01:00
Options: ✔
Notes: 201
Onboarding: completed

### Action Scheduler ###

Complete: 6,442
Oldest: 2024-01-12 10:09:22 +0100
Newest: 2024-01-19 10:32:42 +0100

Failed: 908
Oldest: 2023-03-10 04:02:04 +0100
Newest: 2024-01-19 10:23:45 +0100

Pending: 14
Oldest: 2024-01-19 11:05:16 +0100
Newest: 2024-01-19 21:49:16 +0100

### Status report information ###

Generated at: 2024-01-19 10:39:19 +01:00
`

**Comment by iamgergo** [comment]
Szia!

Szerintem nálatok lesz valami, mert 403/415 választ mi nem dobunk, lehet, hogy egy security plugin vagy tűzfal az oka, aminek nincs sok kösze a Woo verzióhoz. A 415 akkor szokott előfordulni, ha mondjuk a szolgáltató tiltja, korlátozza egy adott IP-ről az elérést.

A `HTTP_SIGNATURE` az IPN kérés során bekerül a server változók közé, az nem egy default server érték.

**Comment by iamgergo** [comment]
Kevertem a 415-öt a 419-cel. Pont nemrég jött egy issue ahol hasonló lehet a gond.

https://github.com/conedevelopment/simplepay-gateway/issues/161

Szerintem egyeztessetek, hátha kiderül mi a gond.
