### ISSUE TITLE
Kétlépcsős fizetési probléma a státuszokkal

### ISSUE THREAD

**Issue by Design-Publica** [conedevelopment/simplepay-gateway#163]
Sziasztok!

Ha be van kapcsolva a kétlépcsős fizetés, akkor a rendelés leadását követen "Fizetés előtt" állapotba kerül (mivel csak előfoglalja az összeget, gyakorlatilag nem történik meg a fizetés), és a kétlépcsős fizetés lezárása csak ebben az állapotban elérhető.

A probléma az, hogy amíg fizetés előtti státuszban van, addig nem küld "Új rendelés" e-mailt sem a vásárlónak, sem az adminnak, mert ekkor nem tekinti késznek a rendelést.

Egy plugin segítségével be tudom állítani, hogy a Fizetés előtt állapotot automatikusan azonnal megváltoztassa Feldolgozás alattra, ekkor az admin is kap értesítőt az új rendelésről, és a vásárló is kap visszaigazolást. Viszon ilyenkor, ha le akarjuk zárni a kétlépcsős fizetést, akkor manuálisan vissza kell állítani Fizetés előttre, mert Feldologzás alattnál nem jelenik meg a lezárás lehetősége. Amivel nem lenne gond, viszont a lezárásra kattinva automatikusan megint Feldolgozás alatt-ra vált (mert ekkor érzékeli késznek a rendelést), így újra kiküldi a vásárlónak a sikeres rendelés e-mailt, ami nagyon zavaró.

Erre esetleg lehetne valami megoldást találni?

1. lehetőség: Engedélyezze a kétlécsős fizetés lezárását "Feldolgozás alatt" státusz-ban is
2. lehetőség: Kétlépcsős fizetés lezárásakor ne Feldolgozás alattra váltson, hanem Teljesítettre (Ez lenne a legjobb megoldás, mert így nem kapná meg újra a vásárló a köszönjük a rendelést e-mailt)

+ Ha pluginnal (Custom Order Status Manager for WooCommerce) létrehozok egy új állapotot, akkor be lehet-e állítani, hogy ebbe a státuszbe kerüljön "Fizetés előtt" helyett ha a vásárló végigvitte a rendelést? Mert ebben az esetben ennél az állapotnál be lehet állítani, hogy a "Payed status" off legyen, így ha jól sejtem ennél engedélyezné a Kétlépcsős fizetés lezárását, de mellette beállítható, hogy erről menjen ki e-mail értesítés. 

Köszönöm előre is a segítséget

**Comment by iamgergo** [comment]
Szia,

Meg fogjuk nézni hamarosan és jelentkezünk!

**Comment by iamgergo** [comment]
@Design-Publica Frissítettem a bővítményt. Valóban volt benne némi anomália, ezt javítottam elérhető az új verzióban.

**Comment by Design-Publica** [comment]
> @Design-Publica Frissítettem a bővítményt. Valóban volt benne némi anomália, ezt javítottam elérhető az új verzióban.

Köszönöm a gyors segítséget, azt megkérdezhetem, hogy hogyan lett javítva? Az 1. vagy a 2. lehetőség lett megvalósítva? Vagy mindkettő?

**Comment by iamgergo** [comment]
Az 1-es pont abban lett javítva, hogy nem a rendelés állapotát figyeli a plugin, hanem azt, hogy valóban megtörtént-e a fizetés.

A 2-es pont szándékosan van úgy ahogy, mert az elvárt működés az, ahogy most van. FIzetés után, csak a virtuális termékeket tartalmazó rendelés vált át teljesítetté automatikusan. Ha ettől eltérő működésre van szükségetek, akkor azt egyedileg tudjátok megoldani, pl.: úgy ahogy fent is írtad.

**Comment by Design-Publica** [comment]
Köszönöm, tesztelés után működik, és engedi a Feldolgozás alatt státusznál is a Kétlépcsős fizetés lezárását.
A teljestett-re álltást is sikerült megoldani egy pluginnal.

Viszont ami még probléma lenne, hogy arra van-e lehetőség, hogy a rendelés leadásakor is azt figyelje, hogy valóban megtörtént-e a fizetés, és magától Feldolgozás alatt állapotba lépjen ekkor a rendelés, ne Fizetés előttre. Ahogy az eredeti problémánál írtam, erre is van pluginos megoldás, hogy a Fizetés előtt státuszt átálltja automatikusan Feldolgozás alatt-ra, hogy kimenjen az értesítés nekünk és a vásárlónak is. Ezzel csak az a gond, hogy ha valaki eljut odáig hogy fizetésnél feljön a SimplePay felülete, de onnan kilép tényleges fizetés nélkül (ekkor Fizetés előtt állapotban van a rendelése), akkor ezt is áltállítja a rendszer Feldolgozás alattra, pedig ez nem valid rendelés, és ezt jó lenne kiszűrni, hogy ne kelljen minden rendelést leellenőrizni a SimplePay adminban, hogy valóban végigvitte-e a fizetést a vásárló.

Köszönöm előre is!

**Comment by iamgergo** [comment]
Elvileg ennek kell történnie.

1. A vásárló fizet, de mivel kétlépcsős a fizetés, az összeg csak befoglalásra kerül
2. Az admin elindítja a fizetés befejezését
3. Erről IPN érkezik a rendszerbe, ami mint a sima vásárlás esetén is, fizetettre állítja a rendelést tehát fizikai termékek esetén "feldolgozás alatt" állapotra
