### ISSUE TITLE
PHP Deprecated Errors

### ISSUE THREAD

**Issue by Jahrnyn** [conedevelopment/simplepay-gateway#164]
- Simplepay Gateway bővítmény verzió: 2.8.3
- WooCommerce verzió: 8.6.0
- WordPress verzió: 6.4.3
- PHP verzió: 8.3.2

### Leírás
Wordpress/Woocommerce oldalunkon Query Monitor plugint használva azt látjuk, hogy az OTP SimplePay Gateway for WooCommerce meglehetősen sok Deprecated hibát generál, ilyet mint például ez:

`Creation of dynamic property Cone\SimplePay\Gateway::$prefix is deprecated

wp-content/plugins/simplepay-gateway-master/src/Gateway.php:118
WPForms\ErrorHandler->error_handler()
wp-content/plugins/simplepay-gateway-master/src/Gateway.php:118
Cone\SimplePay\Gateway->setOptions()
wp-content/plugins/simplepay-gateway-master/src/Gateway.php:71
Cone\SimplePay\Gateway->__construct()
wp-content/plugins/simplepay-gateway-master/src/Gateway.php:358
Cone\SimplePay\Gateway::boot()
wp-content/plugins/simplepay-gateway-master/src/Plugin.php:100
Cone\SimplePay\Plugin::bootGateway()
wp-includes/class-wp-hook.php:324
do_action('plugins_loaded')
wp-settings.php:506`

![image](https://github.com/conedevelopment/simplepay-gateway/assets/89316382/800df5f5-426c-4935-8744-baf0cc970044)

Lehetséges, hogy a plugin még nem kompatibilis az új PHP verzióval, vagy valami mással lehet összefüggésben a "Creation of dynamic property" hiba?

**Comment by iamgergo** [comment]
Hello,

Igen, ez PHP kompatibilitási probléma, egyelőre nem gond, de későbbi PHP verziók esetén az lehet. 
Viszont ebben az ingyenes verzióban ezt már nem tervezzük frissíteni.
