### ISSUE TITLE
5014 hiba Sandbox adatokkal.

### ISSUE THREAD

**Issue by Maxerous1** [conedevelopment/simplepay-gateway#166]
- Simplepay Gateway bővítmény verzió: 2.8.3.
- WooCommerce verzió: 8.6.1.
- WordPress verzió: 6.4.3.
- PHP verzió: 7.4.3.

Amennyiben a sandbox fiókomban lévő MERCHANT és SECRET_KEY -t használom Woocommerce log szerint 5014 hibára fut, viszont, ha az OTP teszt MERCHANT ÉS SECRET_KEY-t használom hibátlanul lefut.

IPN Url megfelelően van bemásolva a sandbox felületen.

Sajnos amíg nem megy a sandboxon nem kapunk hozzáférést a rendbes adminhoz.

**Comment by iamgergo** [comment]
Az 5014-es hiba: "A tranzakció nem megfelelő típusú". Javasoljuk, hogy vedd fel a kapcsolatot a SimplePay ügyfélszolgálatával.
