### ISSUE TITLE
Nincs tranzakció log

### ISSUE THREAD

**Issue by Hu51** [conedevelopment/simplepay-gateway#168]
- Simplepay Gateway bővítmény verzió: 2.8.3
- WooCommerce verzió: 8.6.1
- WordPress verzió: 6.4.3
- PHP verzió: 8.2.5

### Hiba leírása
Naplózás engedélyezése be van pipálva, de semmilyen log nem keletkezik.
Se a sikeresről, se a sikertelen tranzakciókról.
Más log-ok keletkeznek.

**Comment by iamgergo** [comment]
Mi úgy tapasztaljuk, hogy logol. Hiba esetén vagy IPN kérések után is ott a log.

Könnyen lehet, hogy valamilyen lokális probléma áll fenn, sajnos más ötletünk nincs.
