### ISSUE TITLE
instant transzfer kérdés

### ISSUE THREAD

**Issue by ucsendre** [conedevelopment/simplepay-gateway#42]
Sziasztok!

Az OTP mobiltól kaptunk egy tájékoztató hírlevelet azonnali átutalás témában.
Ránk vonatkozóan az alábbi szerpel a lent linkelt oldalon:
"Meglévő ügyfeleinknek a kártyás fizetési lehetőség mellett alapértelmezetten felkínáljuk ezt a fizetési opciót"
https://simplepay.hu/instant-transfer/
Esetleg van erről további információtok?

Köszönöm!

Üdv,
Endre

**Comment by iamgergo** [comment]
Szia!

Nekünk sincs több infónk erről és ahogy nézem a technikai dokumentáció sem valami bőbeszédű.

Ha esetleg lesz több infótok akár ezzel kapcsolatban is, ami esetleg érintheti a bővítményt, akkor szívesen vesszük ha megosztjátok!

Köszi!
Gergő
