### ISSUE TITLE
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by gkovacs82** [conedevelopment/simplepay-gateway#44]
Sziasztok!

Olyan hibába futottam most bele, hogy épp egy adományozó weboldalt kötünk össze az OTP Simplepay fizetési móddal és nyilván csak három adatot kérünk be (vez.név, keresztnév, email cím) az adományozótól, a többi mezőt lekapcsoltuk, hogy ne is jelenjen meg, és ne is legyen kötelező megadni.
Minden esetben, ha nem töltjük a számlázási adatok (cím, ország, megye, város), akkor nem dob tovább a sandbox simplepay oldalra, hanem ezt a hibát dobja: "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."

Amint visszakapcsoljuk az összes mezőt a checkout page-en és kitöltjük, akkor rendben tovább küldd a simplepay oldalra.

Már többször használtam ezt a plugin-t és tökéletesen működött eddig! Hálás köszönet! Szuper plugin!
De más oldalon természetesen nem voltak kikapcsolva a cím és egyéb adatok.

Az OTP simplepay nem kér kötelezően számlázási címet. Más oldalak is használnak OTP Simplepay-t és csak adományozó nevet és e-mail címet kérnek be, mást nem.

Verzió: 2.4.5

Esetleg van erről további információtok? 

Köszönöm!

**Comment by iamgergo** [comment]
Szia!

Hamarosan utánanézek, hogy pontosan melyik mezők lehetnek üresek a szállítási adatokból és milyen formában (null, üres string, stb), és jelzek!

Ha ezt szépen le tudjuk kezelni bővítményen belül, akkor a következő verzióval remélhetőleg ki is mehetne.

**Comment by iamgergo** [comment]
@gkovacs82 Kiment a 2.4.6-os verzió ami lekezeli ezt az esetet is.

Abban az esetben ha a számlázási adatok közül csak az email (ami minden esetben kell) és a nevek vannak jelen (a nevek akár hiányozhatnak is), akkor ezt le tudja kezelni a SimplePay és a bővítmény. Amint egy cím vagy bármi más megadásra kerül, akkor az összes többit is meg kell adni, tehát nem lehet olyan, hogy pl.: email, név, és a város. Mivel a város jelen van, szükséges a cím többi része is.

Teszteltem, és nálam rendben működött, kérlek jelezz vissza ha nektek is rendben és zárom a hibajegyet.

Köszönöm!

**Comment by gkovacs82** [comment]
@iamgergo Nagyon köszönöm!! Szuper, teszteltem az új 2.4.6-os verziót, és tökéletesen kezeli már ezt a ritka, inkább adományozó oldalaknál előforduló esetet (amikor csak ezt a 3 adatot kérjük be: last name, first name, email address).

Köszönöm! Még egyszer a gyors segítséget!
