### ISSUE TITLE
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by KAP-CSC** [conedevelopment/simplepay-gateway#47]
Sziasztok!
Olyan problémám lenne, hogy hiába adom meg a Merchant és a titkosító kulcsot valamint a bolt IPN/IRN URL-jét fizetéskor ezt az üzenet kapom:
"Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."

SimplePay Gateway for WooCommerce: 2.4.6

WordPress: 5.5.3
WooCommerce: 4.7
WordPress memory limit: 256 MB
Nyelv: hu_HU
Szerver információ: Apache/2.4.38 (Debian)
PHP:7.3.21
PHP időkorlát: 30
MySQL version: 5.5.5-10.3.23-MariaDB

Releváns pluginok:
Flexible Shipping
Woocommerce Foxpost Parcel
HuCommerce 
WooCommerce Wholesale Prices

Ezek kikapcsolásával is teszteltem, de ugyanúgy előjön a hiba.
Pénznem megfelelő.
Esetleg okozhatja-e az a problémát hogy a Sandboxban az alapadatoknál az url www nélkül szerepel, az oldal pedig a valóságban mindig szerepel a www ?

log fileban ez szerepel:
PHP Notice:  Undefined index: section in /var/www/clients/client63/web160/web/wp-content/plugins/simplepay-gateway-master/src/Gateway.php on line 301

Köszönöm!

**Comment by iamgergo** [comment]
Szia!

Nem hiszem hogy a www lenne a gond. A log hiba sem ezzel kapcsolatos.

Valami a woo-nál lehet. Esetleg tudunk valahogy egy tesztvásárlást csinálni?

**Comment by KAP-CSC** [comment]
Szia! Természetesen: radiice.hu

**Comment by iamgergo** [comment]
Csináltam 1-2 tesztet és valóban valami nem okés, de nem tudom mennyire kapcsolódik ez a bővítményhez.

A errors log teljesen üres?

**Comment by KAP-CSC** [comment]
Szia!
Nagyon köszi.
Sajnos üres.

**Comment by iamgergo** [comment]
Ha emailen tudsz küldeni egy átmeneti admin hozzáférést akkor még ott rá tudok nézni esetleg.
Valamilyen egyedi dolog lehet ez, mert senki nem jelzett, hogy gond lenne.

Köszi!

**Comment by KAP-CSC** [comment]
Probléma megoldva, köszönjük a segítséget
