### ISSUE TITLE
Simplepay 5014-es hibára fut

### ISSUE THREAD

**Issue by Aledika963** [conedevelopment/simplepay-gateway#49]
Helló! 
Most kezdtem neki az egésznek, és rögtön problémába futottam sajnos. 
Letöltöttem a példa php sdk-t, ami a teszt otp merchant-idvel tökéletesen működik, viszont mikor átírom a saját merchantomra, csere kulcsall mindennel, akkor nem megy végig a folyamat, hanem jön a hibaüzenet, hogy:
Transaction start was failed! és 5014-es hiba. 
Ami érthető is, mivel hiába adtam meg a totál értékét akkor is 0ra fut.

Valaki tudna esetleg segíteni? Vagy futott már hasonló hibába?

Köszönöm előre is!

**Comment by iamgergo** [comment]
Szia!

Ha az SDK-val van gond, akkor az a legegyszerűbb, ha a SimplePaynek jelzed.
Mi nem használjuk az SDK-t semmilyen formában, így segíteni sem tudunk.

Az 5014-es egyébként a "A tranzakció nem megfelelő típusú" hiba, így lehet, hogy a tranzakció jellegénél érdemes a hibát keresni.

**Comment by Aledika963** [comment]
Szia!

Köszönöm a választ :)

**Comment by Gellipapa** [comment]
Üdv! Régen volt már ez a kérdés de azért ide írom a megoldást. Nálam napokban fordult elő és rákerestem az interneten és megtaláltam ezt az issue-t. Hasznos lehet másnak is ez a kis infó.

Teszteléshez a SimplePay weboldalán ezek a sandox adatok használhatóak teljesen ingyen. A lenti adatokkal tökéletesen fog működni az API, kivétel ez alól a IPN mert az sandbox-ban ingyenesen nem tesztelhető.

HUF_MERCHANT értéke: PUBLICTESTHUF
HUF_SECRET_KEY értéke: FxDa5w314kLlNseq2sKuVwaqZshZT5d6
