### ISSUE TITLE
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by Gheldin** [conedevelopment/simplepay-gateway#50]
Sziasztok!
Olyan problémám lenne, hogy hiába adom meg a sandbox fiók Merchant és a titkosító kulcsot valamint a bolt IPN/IRN URL-jét fizetéskor ezt az üzenet kapom:
"Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."

SimplePay Gateway for WooCommerce: 2.4.6
WordPress: 5.5.3
WooCommerce: 4.8

Köszönöm!

**Comment by iamgergo** [comment]
Szia!

Ennek sok oka lehet, nem biztos, hogy közvetlenül a bővítmébyhez köthető.
Milyen hiba van a logban?

Illetve itt van néhány hasonló hibajegy:
#47 és #44

**Comment by Gheldin** [comment]
Szia,
Nincs semmi a logban, valszeg ez az OTP hibája lesz, holnap egyeztetek velük.
Ha megvan a megoldás akkor leírom ide, hátha másnak segít!

**Comment by Gheldin** [comment]
SimplePay rendszerhiba volt, reggelre jó lett!

**Comment by iamgergo** [comment]
Köszi!
