### ISSUE TITLE
simplepay logóra linket rakni

### ISSUE THREAD

**Issue by VortexOfLife** [conedevelopment/simplepay-gateway#51]
Sziasztok, visszadobták ellenőrzésnél a webáruházat ezzel:
A SimplePay logónak egyben linknek is kell lennie és a SimplePay fizetési tájékoztatójára kell mutatnia, ami a következő: http://simplepartner.hu/PaymentService/Fizetesi_tajekoztato.pdf

**Comment by iamgergo** [comment]
Szia!

A beállításokban van egy ilyen opció, ha bepipálod, akkor a fizetésnél link lesz a logo.
Vagy widgetként is elérhető és be lehet szúrni ahova szerednéd.
