### ISSUE TITLE
Kerekítési hiba a kiküldött (első) levélben

### ISSUE THREAD

**Issue by fancsali** [conedevelopment/simplepay-gateway#53]
A fizetés lezárulta után az **első** kiküldött email üzenetben az árak kerekítve jelennek meg (pl. $2.99 helyett $3; így tizedesek nélkül), akkor is, ha USD/EUR a pénznem:

- Ha **csak virtuális** termékek vannak a kosárban, ez az egyetlen kiküldött levél (legalábbis a szóban forgó webshop-ban), és ilyenkor a többi generált dokumentum is hibás árat tartalmaz. (Pl. szamlazz.hu plugin is kerekített árakat tesz a PDF-be)
- Ha van "normál" termék is a kosárban, az első visszaigazolás kerekít, a tobábbi levelek (pl. a rendelés kézzel készre állítása után kiküldött) renben van. Ilyenkor a számla PDF is helyes.

Ha kikapcsolom a SimplePay plugin-t, és más fizetési metódust választok, minden rendben működik.

Jelenleg a rendszer az alábbiak szerint áll össze:
- WP 5.1.6
- PHP 7.1.33
- WooCommerce 3.5.8
- WooCommerce Multi-Currency 2.9.1

**Comment by iamgergo** [comment]
Szia! 

Most csináltam egy tesztvásárlást virtuális termékkel, és én ezt nem tapasztaltam.
Valamint mástól sem érkezett hasonló visszajelzés, amely arra utalna, hogy nem a pontos árat kapja a rendszer.

Ezek alapján szerintem valamilyen egyedi probléma merülhetett fel, sajnos mélyebben nem tudunk utánajárni.
Amennyiben úgy látod, hogy mégis a bővítmény okozza a problémát, szívesen veszünk egy PR-t a javítással.

Köszönöm.

**Comment by fancsali** [comment]
Bocs a necrobump-ért. Csak arra lennék kíváncsi, hogy a Multi Currency
plugin-el együtt tesztelted? Az a gyanúm, hogy azzal akad össze...

**Comment by iamgergo** [comment]
Nem, anélkül teszteltem. Könnyen lehet, hogy ott akad össze valami.
Ha sikerült megoldani és esetleg beküldesz egy PR-t azt megköszönjük!

**Comment by fancsali** [comment]
Hát, ha arra kerül a sor, szívesen. De azért remélem nem kell olyan mélyre
ásnom magam.

Annyit még megkérdezhetek, hogy milyen verzióval/verziókkal teszteltet?
Illetve, megfordítva a kérdést, mi a minimum támogatott verzió WP/Woo/stb
terén nálatok?

**Comment by iamgergo** [comment]
A legfrissebb WP-vel és Woo-val teszteltem. Nem tudom mi a minimum, de az 1-2 évvel ezelőtti verziókkal is rendben ment, azóta nem nagyon változott a kódbázis.
