### ISSUE TITLE
Simplepay - IPN FINISH nem jön vissza a tranzakció végén

### ISSUE THREAD

**Issue by V0072** [conedevelopment/simplepay-gateway#54]
Sziasztok!

Valószínűleg nem a plugin hibája, de  az egész napom ráment a debug-ra és nem látom hogyan lehetne ezt a problémát megoldani. Így ide írok, reménykedve, hogy ti már találkoztatok ilyen esettel.

**A probléma a következő:**
A simple admin console-jában látszik, hogy:

1. sikerül az adott tranzakció, 
2. le is vonja az összeget a vásárló kártyájáról, 
3. majd visszairányítja a simple a webshopra és megkapja a  "köszönjük, hogy nálunk vásárolt" oldalt
4. Viszont az utolsó lépés az IPN (Instant Payment Notification) visszaküldése nem működik. 
5. *grátisz, h a WP nem érzékeli, hogy a fizetés megtörtént és nem küld e-mail az adminnak és a vásárlónak sem (szerencse, hogy a simple küld)

_A vicc, hogy eddig mind sandbox módban, mind "live" módban működött._
**A hiba a simple-ben:**

1. Result NOT200
2. Signature NO_SIGNATURE
3. ResponseIndex 31
4. Finished 2021.01.06 22:15:23
5. IPN URL https://www..........com/?wc-api=wc_gateway_simplepay-gateway
6. Sent IPN hash {"salt":"xxxxxxxxx","orderRef":"xxxxxxx-order-552","method":"CARD","merchant":"OMSxxxxxxxx","finishDate":"2021-01-05T22:26:08+01:00","paymentDate":"2021-01-05T22:25:39+01:00","transactionId":xxxxxxxxx,"status":"FINISHED"}
7. Response status code 503

_Szóval HTTP 503, de nem értem miért._ 

- Server oldalon DEBUG mód (wp szinten ill. simple-pay-plugin szinten is) bekapcsolva és nem látok hibát.
- Error.log-ban nincs hiba.
- A tűzfalat is kikapcsoltam (annak ellenére, hogy eddig bekapcsolt tűzfal mellett is gond nélkül ment a fizetés utáni IPN visszaküldés).
- Apache log: 94.199.53.96 - - [06/Jan/2021:21:03:06 +0100] "POST /?wc-api=wc_gateway_simplepay-gateway HTTP/1.1" 503 - "-" "Apache-HttpAsyncClient/4.1.1 (Java/1.8.0_272)"
- A simple pluginban a merchant kód és a privát kulcs is helyesen van beállítva.
- A server sem blokkok semmilyen IP címet, a szolgáltatónk nem végez karbantartás sem és kiesés sincs.
- HTTPS-ünk (Let's encrypt) is rendben van, így nem értem a fent jelzett NO_SIGNATURE hibát
- A plugin Teszt üzemmódba átkapcsolva, a simple sandbox módjában is ugyanez a helyzet. Fizetés megtörténik, visszairányít, de az IPN-t nem tudja elküldeni. Manuális IPN küldés sem megy (a simple admin/sandbox admin oldaláról sem). A ResponseIndex 31 arra utal, hogy már 31 volt próbálva, ebből én voltam 20x.

Köszönöm, hogy elolvastátok és előre is a segítséget, útmutatást.

**Comment by iamgergo** [comment]
Szia!

Köszi a részletes issuet!

A NO_SIGNATURE hibának nics köze az SSL-hez, ott az a lényeg, hogy a hash amit az SP használ a visszaigazoláshoz, nem található (mivel 503-as hiba van, az csak 200-as válasz esetén van jelen).

Az 503-as hiba a "Service Unavailable". Ennek több oka is lehet, de véleményem szerint, ha a kóddal lenne a gond, akkor 500-at kellene, hogy dobjon – legalább is eddig ez volt a tapasztalat – nem pedig 503-at.

Az megint érdekes, hogy eddig ment, most pedig nem. Nem tudom, hogy történt-e valamilyen frissítés a szerveren vagy a WP-ben, de ennek még érdemes lehet utánajárni. Esetleg kikapcsolni 1-2 plugint ami bekavarhat és úgy próbálkozni manuális IPN-nel.

Innen sajnos többet nem tudunk segíteni. Viszont ha megtaláltad a megoldást és itt visszajeleznél, hogy mi is volt pontosan a gond, azt megköszönjük, hátha másnak is segítséget jelent egy hasonló probléma esetén.

Köszi!

**Comment by V0072** [comment]
Szia,

köszönöm.
Még egy kérdés, a a naplózást hogyan tudom a pluginban bekapcsolni?
Találtam az alábbi az opciót, de nem csinál semmit:

"Naplózás engedélyezése
SimplePay események naplózása - mint az IPN hívások – a megadott előtaggal ellátott fájlokban: simplepay-gateway."

Egy logban sem látok IPN hívásokat. Az HTTP 503 miatt el sem jut a logolásig a plugin?
Ha eljut, hol kellene a file-t látni? Esetleg error.log-ba logol?

**Comment by iamgergo** [comment]
503-as hiba esetén szerintem semmilyen szolgáltatás nem megy, a logolás sem.
Könnyen lehet, hogy valamilyen hiba van valamelyik bővítményben, de 500 helyett 503-at a rendszer, láttunk már ilyet.
Érdemes lehet kikapcsolgatni a bővítményeket egyenként és úgy próbálkozni.

**Comment by V0072** [comment]
Közben megszületett a megoldás :)
All in one seo Bad bot blocker funckiója tiltotta a Java/1 client agent-et amivel a SP küldte az IPN-t. Ezt kikapcsolva -vagy az egentet levéve a tiltó listáról - minden újra működik
