### ISSUE TITLE
Sikeres vásárlás után a rendelés nem vált át completed státuszra

### ISSUE THREAD

**Issue by VortexOfLife** [conedevelopment/simplepay-gateway#56]
Sziasztok,

felraktuk, összekötöttük a webáruházunkat a simplepay-el. a fizetés gond nélkül megy, viszont a vásárlás után nem vált át a rendelés státusza completed-re, hanem wc-processing marad. (A barionnal amúgy ez gond nélkül megy)

Simplepay felületen a rendelés státusza:
Státusz Sikeres - Elszámolásra vár (READY)

Simplepay kommunikációban ezt látom:

IPN üzenetek
OK, Manuális küldés, 2021.01.20 13:10:54 (csináltam pár manuális üzenetet, de semmi különbség)
OK, Manuális küldés, 2021.01.20 13:03:16
OK, Manuális küldés, 2021.01.20 13:00:06
OK, Lezárás, 2021.01.20 10:56:44

Elküldött levelek
OK, Vásárlói lezárás, 2021.01.20 10:56:41
OK, Kereskedői lezárás, 2021.01.20 10:56:41

Bekapcsoltam a naplózást wp-ben is és a plugin-ben is.  A wp-content/debug.log alatt képződik is a naplófájl, de semmi bejegyzést nem látok simplepay-gateway se más hasonló előtaggal, viszont mindenféle más rendszerüzenet van benne. Az OTP is jóváhagyta már a webáruházat a tesztelés után, meg ugye az ügyfelek is vásárolnak, de mintha valahol megakadna a történet. Manuálisan kell jóváhagynunk a rendeléseket.

Kikapcsoltam a BBQ tűzfalat is, semmi különbség.

Tudtok ezügyben valami tanácsot adni?

Köszi
Z.

**Comment by VortexOfLife** [comment]
Megtaláltam a /wp-content/uploads/wc-logs/ alatt a naplókat, mindegyikben ilyenek vannak:
2021-01-20T09:04:42+00:00 INFO Az IPN hívás megtörtént.
2021-01-20T09:56:42+00:00 INFO Az IPN hívás megtörtént.
2021-01-20T12:00:06+00:00 INFO Az IPN hívás megtörtént.
2021-01-20T12:03:16+00:00 INFO Az IPN hívás megtörtént.
2021-01-20T12:10:54+00:00 INFO Az IPN hívás megtörtént.

sehol semmi hiba.

Z.

**Comment by iamgergo** [comment]
Szia!

Ennek pontosan így kell történnie ahogy leírtad.

A `processing` akkor van ha megtörtént a fizetés és teljesíteni kell a rendelést.
A `completed` akkor van ha minden kész, ki van szállítva, nincs több teendő.

https://docs.woocommerce.com/document/managing-orders/

Ha csak virtuális/letölthető termék van a rendelésben, az más kérdés, ott lehet kivétel. Abban az esetben van egy hook, amivel be tudjátok álltani a kívánt rendelési állapotot az adott fizetési metódus után.

```php
add_filter('woocommerce_simplepay-gateway_process_payment_order_status', function ($status, $order) {
    return 'processing';
}, 10, 2);
```
