### ISSUE TITLE
Ha a rendelés tartalmaz 0 Ft értékű terméket a SimplePay nem tudja lekezelni a hívást.

### ISSUE THREAD

**Issue by kis-szolgyemi** [conedevelopment/simplepay-gateway#57]
Kedves @conedevelopment Csapat,

Ez nem a bővítményetek hibája, csak ott sokkal egyszerűbb volt megoldanom, mint a SimplePayen átverekedni azt, hogy a 0 Ft-os termékek ne okozzanak problémát a fizetési tömb fogadásakor :) ezért egy 2 soros fejlesztési ötletet javasonék a számotokra:

**// Háttér és a probléma oka**
Egy woocommerce webáruházban a különböző áfatartalmú termékeket tartalmazó akciós csomagok létrehozására egy Bundle kezelő plugint telepítettünk, hogy a számlára jó áfatartalommal kerülhessenek fel a csomagban lévő termékek. Ez úgy működik, hogy az akciós csomag termék nulla forinttal kerül be a rendelés törzsébe és a csomagban lévő termékek egyesével hozzáadásra kerülnek és minegyikből arányosan levonódik a százalékos kedvezmény a megfelelő áfatartalom megtartása mellett.

Emiatt amikor ezt a csomagot kártyával ki akarta valaki fizetni, akkor a SimplePaynek átadott rendelésadatok közé bekerült a 0 Ft-os csomag is, ami emiatt elhasalt "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra." hibaüzenetel a fizetési folyamat.

**// Megoldási javaslat**
Igazából ez a hiba rendkívül egyszerűen kivédhető, hiszen a 0 Ft-os terméket nem kell soha kifizetnie a vásárlónak, így annak egészen biztosan semmilyen hatása sem lesz a fizetendő összegre, így két extra sorral orvosolni tudtam a problémát.

Mindössze a "PaymentPayload.php" fájlban lévő "protected static function items(WC_Order $order)"-be kellett az $items[] tömb előállítását egy if feltételbe tenni, hogy csak akkor tegye bele a SimplePaynek küldött adatcsomagba a terméket, ha az nem nullába kerül:
 

```

   /**
     * Serialize the items.
     *
     * @param  \WC_Order  $order
     * @return array
     */
    protected static function items(WC_Order $order)
    {
        return array_reduce($order->get_items(), function ($items, $item) {
            $product = $item->get_product();
            $quantity = ceil($item->get_quantity());

          // 0 értékű termékek figyelmen kívül hagyása a SimplePaynek átadott rendelésadatokból
          // feltétel eleje
           if ( ($item->get_total() + $item->get_total_tax() ) != 0) {

                $items[] = [
                    'tax' => 0,
                    'amount' => $quantity,
                    'title' => $product->get_name(),
                    'description' => $product->get_description(),
                    'ref' => $product->get_sku() ?: $product->get_id(),
                    'price' => ($item->get_total() + $item->get_total_tax()) / $quantity,
                ];

            };
           // feltétel vége

            return $items;
        }, []);
    }

```

 

Mivel ez a 0 Ft-os termék helyzet más esetben is lehet előfordulhat, szerintem érdemes egy ehhez hasonló ellenőrzést beletennetek egy következő frissítésbe, hogy más ne fusson bele ilyen hibába.

Mesés napot, Ákos

**Comment by iamgergo** [comment]
Szia @kis-szolgyemi ,

Köszi a részletes hibajegyet és a javasolt megoldást is!

Az a helyzet, hogy ez már a sokadik ilyen jellegű áthidalás lenne, és ahogy te is mondtad, a megoldást a SimplePay tudja előteremteni.

Bár igaz, hogy egyszerűbb fixet én sem tudok erre a problémára, azt hiszem, jelen esetben nem túl jó megoldás, hogy a rendelésben szereplő termékek eltérnek a Woo és a SimplePay szintjén.

Érdeklődni fogunk, hogy van-e szándék a SP részéről, hogy ezeket javítsák, vagy arra számíthatunk amire eddig is: egy középszerű szolgáltatásra...sajnos.

Köszi!

**Comment by kis-szolgyemi** [comment]
Szia @iamgergo , sikerült is megtalálnom, hogy hol a probléma, legalábbis ezzel a módosítással (ami ebbe a PR-be bele is írtam: #68 ) hiba nélkül tovább ment a SimplePay oldalára a fizetési folyamat, hiszen az összegzésből eleve ki lettek hagyva a 0 értékű termékek, így nem okozhattak problémát a tömb fogadásakor.
