### ISSUE TITLE
A pénztár oldal végösszeg eltér a simplepay oldal összegétől

### ISSUE THREAD

**Issue by JoePatai85** [conedevelopment/simplepay-gateway#59]
Azt szeretném jelezni, hogy egy olyan hibával szembesültem, hogy a pénztár oldal vég összesen mezője nem egyezik meg a simple pay oldalra átirányított összeggel. Használok egy Woocommerce Custom Product Addons az Acoweb-től amiben szépen fel vannak a különböző dolgok építve és szépen össze is adja a különböző értékeket a különböző feltételek alapján. Eddig nem volt ilyen nemű problémám, csak nem rég volt egy vásárlás az oldalon és nem számolta hozzá az extra költséget a simple pay fizetési oldalán.

Segítségedet előre is köszönöm.

![checkout_page_summary](https://user-images.githubusercontent.com/78963562/107771463-15bae500-6d3b-11eb-8fd6-71b1ad08cc80.png)
![simplepay_page](https://user-images.githubusercontent.com/78963562/107771470-181d3f00-6d3b-11eb-92a1-87d8ee71818f.png)

**Comment by iamgergo** [comment]
Szia!

Sajnos nem tudunk kompatibilitást garantálni nem hivatalos bővíményekhez.

Elsőre úgy tűnik mintha a kiegészítő nem egy klasszikus kosárelemnént lenne kezelve, így ezt nem tudjuk általánosan lekezelni. De mélyebben nem ástuk bele magunkat.
