### ISSUE TITLE
Rendelés állapotának módosítása

### ISSUE THREAD

**Issue by powerbuldog** [conedevelopment/simplepay-gateway#60]
Sziasztok!

Megoldható lenne egy olyan lehetőség, hogy állítható legyen a sikeres fizetés milyen állapotba rakja a rendelést? (Feldolgozás alatt, Teljesítve)
A mi webshopunk csak olyan rendelést fogad amit személyesen lehet átvenni, így minden rendelés a fizetés után teljesített állapotba kellene kerülnie. 

Próbáltam egy előző issueban leírt módot: 

add_filter('woocommerce_simplepay-gateway_process_payment_order_status', function ($status, $order) {
    return 'completed';
}, 10, 2);

Illetve: 

add_filter( 'woocommerce_simplepay-gateway_process_payment_order_status','simplepay_gateway_order_status_callback', 10, 2 );
function simplepay_gateway_order_status_callback( $status, $order ) {
    return 'completed';
}

De sajnos nem módosította az állapotot, maradt processing.

**Comment by iamgergo** [comment]
Szia!

Elírtam a hook nevét:

```php
add_filter('woocommerce_payment_complete_order_status', function ($status, $id, $order) {
    return 'completed';
}, 10, 3);
```

Ezzel nézd meg, hátha.
