### ISSUE TITLE
Sipmle pay cURL hiba? 

### ISSUE THREAD

**Issue by laverde1** [conedevelopment/simplepay-gateway#61]
Sziasztok! 

A tiétek a második simple pay bővítmény amit telepítettem az oldalunkra: 
laverde-juice.com
Sajnos egyikkel sem indul el a fizetés tesz üzem alatt sem. 
Az első bővítménynél az okozta a hibát, hogy a tárhely szolgáltató (web-server) cak a 7.2-es cURL-t támogatja/engedélyezi, a 7.6-ost nem. A Coone simple pay bővítményével is lehet ugyanez a probléma, ami miatt nem lép tovább a fizetési felületre. 
Sajnos hiba üzenetet nem küld semmit, csak kis gondolkodás után visszagörget az oldal tetejére. 

Köszönöm a választ és a segítséget!

**Comment by iamgergo** [comment]
Szia!

Nem a bővítmény kezeli a cURL-t hanem a szerver, így nem hiszem, hogy ez a bővítmény oldalán lenne gond. 

Azt még érdemesnek tartom megjegyezni, hogy a cURL 7.6-is többb mint 20 éves, _lehet_, hogy frissíteni kellene.

A hibát sok minden okozhatja, első körben érdemes ellenőrizni, hogy a szerződés rendben van-e, illetve nem volt-e szolgáltatás kiesés.

Innen egyenlőre többet sajnos nem tudunk mondani.
