### ISSUE TITLE
Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra.

### ISSUE THREAD

**Issue by Pboszormenyi** [conedevelopment/simplepay-gateway#62]
Sziasztok!

A potemix.hu oldalon beépítettem a plugint, működik is a back-end, viszont a fizetés véglegesítésénél ezt a hibaüzenetet dobja.

A probléma leírása teljesen megegyezik a #47-es ticketben leírtakkal, csak ott nem volt részletezett válasz/megoldás.

Sajnos az error log nálam is üres.

Ha tudtok segíteni, előre nagyon hálás lennék! :)

Szép napot!

**Comment by iamgergo** [comment]
Szia!

A #47-es mellett, az #50-es is hasonló hiba. Egyik esetben sem a bővítmény oldalán volt a gond.
Érdemes lehet várni, ha mondjuk később sem lesz jó akkor, már lehet kutakodni.

**Comment by Pboszormenyi** [comment]
Szia!

Köszönöm a gyors választ. Mindkét esetben az OTP oldalán volt a gond? Esetleg Woo? Hátha addig tudnék kutatni én is. :)

Köszi!

**Comment by iamgergo** [comment]
Woo esetén is lehet gond, mivel adhat át olyan értéket a SimplePay-nek amit az nem tud feldolgozni, de ezeket már korábbi hibajegyekben sikerült lefedni, aztán lehet találtatok valami újat :).

Érdemes lehet a checkout mezőkkel játszani, lehet hogy ott van valami olyan formátum amit a SimplePay nem fogad be vagy nem dokumentált, esetleg mi nem figyeltünk rá.

A SimplePay nagyon sajnos nem egy stabil szolgáltatás, így lehet, hogy itt is (mint az említett hibajegyekben) csak kiesés, vagy hibás/rossz szerződés okozza a gondot.

**Comment by Pboszormenyi** [comment]
Igen, ezt nem írtam, hogy friss a szerződés, friss a fiók, és eddig még nem álltunk a SimplePay csapattal semmilyen kapcsolatban. Emiatt a kiesést inkább kizárnám (2 napja ugyanez a helyzet), inkább a szerződéses para a valószínűbb. Elképzelhető, hogy eleresztek egy mailt az IT supportnak, írok fejlemény esetén. 

Köszi!

**Comment by Pboszormenyi** [comment]
Szia Uram!

Megoldódott a probléma, az OTP oldalán volt a gond most is.

Idézem: "Meg is van a gond, egy hibás fiókbeállítás miatt nem ment a fizetés. Ezt most javítottam és le is teszteltem az oldalt."

Így zártam is a ticketet, és köszönöm a segítséget! :)
