### ISSUE TITLE
WooCommerce SimplePay bővítményt nem tudom bekapcsolni a Word Press sablonomban?!

### ISSUE THREAD

**Issue by miklosf1** [conedevelopment/simplepay-gateway#64]
Tisztelt Támogatás!

EZt a hibaüzenetet írja ki amikor be szeretném kapcsolni a WooCommerce bővítményt a WordPress sablonomban http://megvalositomazalmomat.info az oldalamon:
"A bővítmény bekapcsolása nem sikerült, mert végzetes hibát generált."

Innen töltöttem le: https://simplepay.conedevelopment.com/a-woocommerce-simplepay-bovitmeny-telepitese majd fel a zip file-t a WordPressbe.

Kérem tisztelettel a segítségüket!

Köszönettel & üdvözlettel,
Forgács MIklós
+36709338145

**Comment by iamgergo** [comment]
Kedves Miklós,

Ennek sok oka lehet, pl.: nincs WooCommerce telepítve a oldalon, elavult a PHP vagy WordPress verzió.
Érdemes megnézni az error logot és az alapján tovább lépni, ez ügyben sajnos nem tudunk segíteni.

**Comment by miklosf1** [comment]
*Kedves Gergő!*

Woo Commerce CSAk mint bővítményt telepítettem.
EZT írja még ki:
"Kérünk, aktiváld a WooCommerce bővítményt mielőtt a SimplePay fizetési
kaput használod!"

Kellett volna még mást is telepítenem a bővítmény előtt?

A WordPress verzióm is naprakész.

KÖszönöm,


*Forgács Miklós*
*Megvalósítom az Álmomat <http://megvalositomazalmomat.info>*
*Tel. +3670/933-8145 *







D. Nagy Gergő <notifications@github.com> ezt írta (időpont: 2021. febr.
24., Sze, 14:07):

**Comment by iamgergo** [comment]
Ahogy az üzenet is írja, nem csak telepíteni, de aktiválni is kell a WooCommerce-t.

**Comment by miklosf1** [comment]
IGEN, és hogy lehet aktiválni a Bekapcsoláson kívül? Mert a bekapcsolást
nem engedi  ezt a hibaüzenetet kiírva:
"A bővítmény bekapcsolása nem sikerült, mert végzetes hibát generált."

köszönöm

*Forgács Miklós*
*Megvalósítom az Álmomat <http://megvalositomazalmomat.info>*
*Tel. +3670/933-8145 *







D. Nagy Gergő <notifications@github.com> ezt írta (időpont: 2021. febr.
24., Sze, 14:33):

**Comment by iamgergo** [comment]
Ha a WooCommerce bekapcsolása során merül fel ez a hiba, úgy ennek az oka bármi lehet.
Amennyiben sikerül bekapcsolni a Woo-t, úgy jó eséllyel a SimplePay-t is aktiválni tudja, mivel az egyetlen függősége a Woo.

Sajnos, mi nem tudunk innen többet segíteni, reméljük hamarosan megoldódik.

**Comment by miklosf1** [comment]
köszönöm. AZ nem volt világos, hogy előbb a WooCommercet is telepítenem
kell... nem volt sehol leírva a Simple Pay linken.

folyamatban van a dolog... csinálom.

KÖszönöm

*Forgács Miklós*
*Megvalósítom az Álmomat <http://megvalositomazalmomat.info>*
*Tel. +3670/933-8145 *







D. Nagy Gergő <notifications@github.com> ezt írta (időpont: 2021. febr.
24., Sze, 14:54):
