### ISSUE TITLE
Más összeget von le a kártyáról (talán kerekítési hiba?) 

### ISSUE THREAD

**Issue by kalozpepi** [conedevelopment/simplepay-gateway#65]
- Simplepay Gateway bővítmény verzió: 2.4.9
- WooCommerce verzió: 5.0.0
- WordPress verzió: 5.6.2
- PHP verzió: 7.3.27

### Amikor a vásárlók simple pay-el fizetnek, a kártyáról levont összeg 2-3 forintban eltér a tényleges vételártól. A legutóbbi esetekben: 21090 Ft helyett 21088-at, 11200 helyett 11198-at, 7250 helyett 7247 Ft-ot vont le. Azt gondolom, hogy valami kerekítési probléma lehet. Az áruházban van 27%-os és 5%-os áfatartalmú termék is. Így a szállítás áfája a szabályzás miatt a vásárolt termékhez képest változik (ha valaki könyvet vesz, ami 5% áfás, a szállítási díjnak is 5%-os áfatartalmúnak kell lennie.) Namost ezért én a szállításnál bruttó összeget vagyok kénytelen beállítani, hiszen nekem ugyanannyit kell kifizetnem a postán ha könyvet küldök, ha mást. 
Lehet, hogy az befolyásolja a végeredményt, hogy beállítottam a szállítási plugint, hogy bruttó összeget számoljon, bár nem tudom, hogy ez miben járulna ahhoz hozzá, hogyha a kosárban x Ft értékű termék van, (teljesen mindegy, hogy mennyi áfát tartalmaz, a végösszeg mindig kerek), miért nem azt az összeget vonja le a kártyáról a rendszer?

Tudna valaki tanácsot adni, mit tegyek?
Előre is köszönöm.
Veronika

**Comment by iamgergo** [comment]
Kedves Veronika,

Nem találkoztunk még hasonlóval, így gyanítom, hogy valmilyen egyedi beállítás lehet az oka.

A bővítmény nem kerekíti az árakat, azokat semmilyen formában nem módosítja, ellenben mindig a bruttó árakat kezeli, erről [itt írunk bővebben](https://simplepay.conedevelopment.com/a-simplepay-bovitmeny-korlatai).

Ellenben a rendelés összegét a bővítmény nem  kosárban mutatott összeg alapján veszi, hanem az ott található termékek és szállítás alapján újra kiszámolja. Erre mindenképpen szükség van, ezen nem tudunk változtatni.

Talán az lehet az oka, hogy a kosár értékét kerekíti valamiért egy bővítmény vagy egy egyedi kód, de amikor egyenként kiszámolja a termékek bruttó árát a SimplePay bővítmény, nem a kerekítettet adja.

Megoldás lehet, hogy a termékeknél is egy kerek bruttó árat adtok meg, így a végösszeg is midig kerek lesz.
Persze nem tudom, hogy egy mennyire kivitelezhető a ti esetetekben.

Sajnos innen ennyit tudunk segíteni.

**Comment by kalozpepi** [comment]
Köszönöm, ez is segítség volt!!!
