### ISSUE TITLE
IPN hiba

### ISSUE THREAD

**Issue by kalozpepi** [conedevelopment/simplepay-gateway#66]
Sziasztok! 
Újabb kérdéssel fordulok hozzátok. Sajnos valamiért mindne vásárlás után IPN hibát dob a Simple Pay, a következő üzenettel. (A vásárlás közben rendben lemegy de mégsem kerek a dolog valamiért)

Eredmény CONTENTNOTMATCH
Signature NO_SIGNATURE
Fogadott válasz A rendelés nem található.
IPN újrapróbálása 436470402
Újrapróbálva 11
Index 14
Időpont 2021.03.24 11:32:58
IPN URL https://.../?wc-api=wc_gateway_simplepay-gateway  **(a ... a domainnevet jelzi)**
Elküldött IPN tartalma {"salt":"3iDjr73oqO8PHuCKKNkWqlkApFGA0WC0","orderRef":"wc-KZ-60","method":"CARD","merchant":"OMS5044001","finishDate":"2021-03-23T23:32:52+01:00","paymentDate":"2021-03-23T23:31:25+01:00","transactionId":153411075,"status":"FINISHED"}
Válasz HTTP kódja 200

Én pontosan azt a linket másoltam be a Simple adminba, amit a webshop adminfelületén a Simple Plugin mutatott. Kellett volna valami mást is vagy máshogyan beállítanom? 

Előre is köszönöm a segítséget.
V.

**Comment by kalozpepi** [comment]
Közben kiderült, hogy mi lehet a hiba, proxi szerveren fut a webshop... gondolom, ez kavarhat be erőst....

**Comment by iamgergo** [comment]
Szia!

A "A rendelés nem található." hibaüzenet akkor van, ha valamilyen okból kifolyólag az IPN üzenetből nem tudja visszavezetni, hogy melyik rendelésre vonazkozik az IPN hívás.

Nem tudom, hogy mennyi köze van ennek a proxy-hoz, lehet érdemes lenne a rendelés előtaggot módosítani, mondjuk nagybetűsre, megnézni, hogy azzal megy-e, stb.

Elvileg ezzel sem szabadna, hogy gond legyen, de futottunk már hasonlóba.

**Comment by kalozpepi** [comment]
Köszönöm, kipróbálom!
Közben találtam a neten cloudflare-el kapcsolatban hasonló esetet (csak az paypal-os IPN volt), most megpróbáljuk az IPN URL-t kivenni a proxy alól... hátha

**Comment by kalozpepi** [comment]
Sajnos a proxi alól kivétel nem hozott megoldást, továbbra is IPN hiba van.. Nincs valakinek valami ötlete esetleg? Találkoztatok hasonlóval?

**Comment by iamgergo** [comment]
Igen, sejtettem, hogy nem az a gond. Ez a rendelés prefixed: `wc-KZ-`?

**Comment by kalozpepi** [comment]
A rendelésnél csak KZ a prefix. Ez lehet a gond? Mondjuk erre nem gondoltam.

**Comment by iamgergo** [comment]
Az IPN-ben látszik, hogy a rendelés ID-ja `wc-KZ-60`, szerintem itt csúszik el valahol.

**Comment by kalozpepi** [comment]
igen most dolgozom rajta... ez lehet a gond, majd referálok, hogy mire jutottam

**Comment by kalozpepi** [comment]
sajnos nem nyert.. összefésültem a prefixeket (wc-KZ), csináltam tesztvásárlást, de sajnos semmi változás

Eredmény CONTENTNOTMATCH
Signature NO_SIGNATURE
Fogadott válasz A rendelés nem található.
Index 2
Időpont 2021.03.25 16:25:31
IPN URL https://kalakazenebolt.hu/?wc-api=wc_gateway_simplepay-gateway
Elküldött IPN tartalma {"salt":"Twy9cF990QCNGLPLmtux69xUOc5Cv9gV","orderRef":"wc-KZ-69","method":"CARD","merchant":"OMS5044001","finishDate":"2021-03-25T16:25:27+01:00","paymentDate":"2021-03-25T16:24:13+01:00","transactionId":153816835,"status":"FINISHED"}
Válasz HTTP kódja 200

most már

**Comment by iamgergo** [comment]
Kérlek vedd fel velünk a kapcsolatot itt: hello@condevelopment.com. Hátha ki tudunk találni valamit.

**Comment by kalozpepi** [comment]
nagyon köszönöm!!!

**Comment by tolvajsanyi** [comment]
Sziasztok! 

Ugyanebbe a hibába éppen ma futottam bele. Lett valami megoldás? Köszönöm szépen előre is a válaszotok.

**Comment by iamgergo** [comment]
Szia!

A HTTP válasz 403-as, tehát feltehetően valami blokkolja a kérést.
Ez lehet egy bővítmény vagy a tűzfal is.

**Comment by tolvajsanyi** [comment]
Igen, időközben a tárhelyszolgáltatómmal is beszéltem, akartam is írni egy updatet, csak gyorsabb voltál :) A Bad Bots beállítás kavart be a tárhelyen, amit kikapcsolva megszűnt a probléma. Köszönöm a válaszod.
