### ISSUE TITLE
Fee számítás

### ISSUE THREAD

**Issue by powerbuldog** [conedevelopment/simplepay-gateway#67]
- Simplepay Gateway bővítmény verzió: 2.4.11
- WooCommerce verzió: 5.1.0
- WordPress verzió: 5.7
- PHP verzió: 7.3.27

### Leírás
Sziasztok. 

Létezik egy olyan, hogy 'fee' meta adat ami növeli a rendelés végösszegét. Ám az ezzel növelt összeg nem kerül átadásra a Simple felé. (Pl nálunk a Payment Gateway Based Fees nevű kiegészítő segítségével extra költséget számolunk a rendelés végére eltérő összegben a fizetési mód függvényében. )

Rendelés XML-be ez így kerül be. 
<OrderTotal>15050</OrderTotal>
<FeeTotal>1250</FeeTotal>

Esetleg ha lehetséges bekerülhetne ennek a fee-nek is a számítása a végösszeg átadásánál, amennyiben van értéke. 

Egy ilyesmi kóddal ez elvileg számolható, és hozzáadható lenne a végösszeghez. 

	  //Fee as discount 
	  foreach( $order->get_items('fee') as $item_id => $item_fee ){

		// The fee name
		$fee_name = $item_fee->get_name();

		// The fee total amount
		$fee_total = $item_fee->get_total();

		// The fee total tax amount
		$fee_total_tax = $item_fee->get_total_tax();
		}
 
      $total_fees = ceil(abs($fee_total));;

### Reprodukáláshoz szükséges lépések

Payment Gateway Based Fees and Discounts for WooCommerce
https://wordpress.org/plugins/checkout-fees-for-woocommerce/

Be kell kapcsolni, és a megfelelő fizetési mód mellé be kell állítani a Fee value-t Fixed type-al. Fee title lehet bármi, a mi esetünkben szállítási díjnak írtuk ki.

**Comment by iamgergo** [comment]
Szia!

Valóban, nem volt lekezelve ez az eset.

A v2.4.12-es verzióban már hozzáadtuk ennek a számítását.

Kérlek frissítsétek a bővítmény, és ha lehet jelezzetek vissza, hogy valóban működik-e.

Köszi!

**Comment by iamgergo** [comment]
https://github.com/conedevelopment/simplepay-gateway/commit/cae464cb3fd29d74c616e1e287f4941d7fb46dae
