### ISSUE TITLE
Instant Utalás fizetési mód támogatása

### ISSUE THREAD

**Issue by marceldarvas** [conedevelopment/simplepay-gateway#70]
- Simplepay Gateway bővítmény verzió: 2.4.13
- WooCommerce verzió: 5.3
- WordPress verzió: 42
- PHP verzió: 7.4

### Leírás

Az instant utalásos fizetés pár hete elérhetővé vált a legtöbb kereskedő számára, 1 vásárló a következő sikeres vásárlást küldte vissza, de rendelés mégis sikertelen volt.

Jó lenne elkülöníteni a fizetési módokat utalásos fizetések esetén, hogy ne legyen megzavaró se backend, se a számlázás kapcsán.
Esetleg 2 fizetési mód lehetősége?

### Reprodukáláshoz szükséges lépések

/SimplePay OTP/src/Payloads/PaymentPayload.php a hiányos handler.

[DATETIMEINFO] INFO Az IPN hívás megtörtént.
{"salt":"[UNIQUECODE]","orderRef":"[ORDERID]","method":"WIRE","merchant":"[MERCHANTID]","finishDate":"[DATETIMEINFO]","paymentDate":"[DATETIMEINFO]","transactionId":[TRANSACTIONID],"status":"FINISHED"}

30p után:
Ki nem fizetett rendelés visszamondva – időkorlát elérve. Rendelés állapota Fizetés előtt volt, majd Visszamondva lett.

**Comment by iamgergo** [comment]
Szia!

Köszi az issuet.

Tehát jól értem, hogy az lenne a cél, hogy két fizetési opció jelenjen meg a checkoutnál, amit a user ki tud választani?
Az egyik a kártyás a másik az utalásos?

**Comment by marceldarvas** [comment]
Hát igazából egy ötlet így checkout-ra nézve, mivel nem lehet az OTP-nél külön fizetési módra irányítani a vásárlót, azt maguknak kell kiválasztani.
De amiatt lenne érdemes 2 fizetési mód, hogy a IPN válasz alapján a számlázók pl. Billingo esetén be lehessen map-ezni a megfelelő fizetési módot és így a vásárló is "barátságosabban" lássa a rendeléseknél

**Comment by iamgergo** [comment]
Egyenlőre sajnos nem úgy néz ki, hogy érdemben lesz időm ezzel foglalkozni.

De ha úgy látod, hogy van egy megoldásod ami működik, akkor nyugodtan nyiss egy PR-t.

Köszi!
