### ISSUE TITLE
"Visszalépés a kereskedő oldalára"

### ISSUE THREAD

**Issue by marceldarvas** [conedevelopment/simplepay-gateway#71]
- Simplepay Gateway bővítmény verzió: 2.4.13
- WooCommerce verzió: 5.3
- WordPress verzió: 42
- PHP verzió: 7.4

### Hiba leírása

Az OTP oldalán nem valami jó UX, hogy nem lehet visszalépni a fizetési lehetőségek között, ha már ki van választva az azonnali utalás például.

Két lehetőséget adnak ha valaki a vissza gombbal próbálkozik. 

1. fizetés folytatása
2. visszalépés a kereskedő oldalára

Az utóbbi esetében a webshopra visszatérve, visszamondott rendeléssel fogad, pedig nem járt le az időkorlát. De nem engedi a fizetést újrakezdeni, csak a "Kérjük vegye fel a kapcsolatot" szöveget adja.

Így csak manuálisan lehet a Rendeléseknél a fizetési státusz módosítani "Fizetés előtt"-re majd a 'számlát' újraküldeni a fizetési linkkel.

**Comment by iamgergo** [comment]
Jogos, ezt itt javítottam: https://github.com/conedevelopment/simplepay-gateway/commit/4ea4f6399d3ec2d50675f726ac44e96809f74de8

Hamarosan megy egy release.

Köszi!
