### ISSUE TITLE
Kedvezményt nem veszi figyelembe

### ISSUE THREAD

**Issue by Csutszika** [conedevelopment/simplepay-gateway#72]
- Simplepay Gateway bővítmény verzió: 2.4.13
- WooCommerce verzió: 5.2.2 
- WordPress verzió: 5.7.1
- PHP verzió: #.#.#

Üdvözletem!

Discount Rules for WooCommerce bővítményt használjuk %-ban megadott kedvezmények levonására. (A bővítmény elérhető a Wordpress hivatalos bővítmény oldalán.) A termékek variálható virtuális termékek. A pénztár oldalon végösszegben szépen megjelenik a levonás, azonban a SimplaPay a kártyáról a termék teljes árát vonja le, és ezzel egyidejűleg a Billingo kiállítja a számlát a kedvezményes árról.

Egy termék:
https://zsilipfestotanoda.com/termek/nyarelo-akriltanfolyam-majus-29-tol-szemelyes-reszvetellel/

Segítségüket előre is köszönöm!

Szanyi Judit
+36 70 364 1728

**Comment by iamgergo** [comment]
Kedves Judit,

Sajnos nem tudunk biztosítani kompatibilitást más bővítményekkel, de azért megnéztem hátha van rá megoldás.

Sajnos nincs, nem tudunk ez ügyben segíteni. Nem mennék bele a részletekbe, de ez részben a WooCommerce részben pedig a SimplePay korlátai miatt van.

Nem tudom, hogy mennyire lehet kuponokkal kiváltani a discount szabályt, de ha igen, akkor azzal biztosan megy a kedvezményes ár.
