### ISSUE TITLE
Sikertelen kártyaadat teszt hiba

### ISSUE THREAD

**Issue by Gheldin** [conedevelopment/simplepay-gateway#73]
- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 5.3.0
- WordPress verzió: 5.7.2
- PHP verzió: 7.3

Sikertelen kártyaadat sandbox tesztelésnél nem dobja a vásárlót hibaüzenet woocommerce oldalra, hanem helyette visszaküldi a Pénztár/checkout oldalra.
Mi lehet a probléma? 
Error logba semmi.

**Comment by iamgergo** [comment]
Ha sikertelen a fizetés, akkor visszadobja, hogy próbálja meg újra.

A woo-n nincs kifejezetten hibaüzenet oldal, a pénztár oldalon kell, hogy megjelenjen a hibaüzenet, ez pedig téma függő is lehet, hogy megjlenik-e vagy sem.
