### ISSUE TITLE
5346-os hibakód

### ISSUE THREAD

**Issue by concretepillow** [conedevelopment/simplepay-gateway#77]
Sziasztok!

Fizetési próbálkozaáskor ezt írja ki az oldal: "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."

- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 3.9.2 
- WordPress verzió: 5.2.9
- PHP verzió: 7.4

A logban ezt találtam : INFO Request is invalid: {"errorCodes":[5346],"salt":"lKTETWAC***************","merchant":"OMS518******","orderRef":"wc-8184","currency":"HUF","total":0.0}

De nem lelem a simple dokumentációjában, hogy ez a hibakód mit takar. :(

A wooccommerce elég öregecske, de kb. két hete még simán működött a simple az oldalon. Jelen pillanatban nem tudom mi lehet a gond.

**Comment by iamgergo** [comment]
Szia!

Gyanítom, hogy az a total: 0.0 kavar be, mivel nem lehet a rendelés, vagy termék összege 0.

A 5346-as hibát én sem találom, érdemes lehet megkérdezni őket.

Ha esetleg kapsz választ, olyat ami használható, akkor lehet be tudunk építeni valamit a bővítménybe, de ebben most nem vagyok biztos.

Köszi!
