### ISSUE TITLE
Eurós fizetéskor nullás áron próbálja tovább küldeni a tranzakciót

### ISSUE THREAD

**Issue by AttiZK** [conedevelopment/simplepay-gateway#78]
- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 5.4.0
- WordPress verzió: 7.2
- PHP verzió: 7.3.20

Sziasztok,

Köszi szépen a plugin-t és a munkátokat, nagyon hasznos és nagyon örülök, hogy létezik egy ilyen. 

Ügyfelem kérése az volt, hogy legyen eurós a shop. Miután telepítettem a plugint és bekapcsoltam a simple fizetési módot azt találtam, hogy forintos fizetésnél gond nélkül működik minden, log:

2021-07-21T11:22:05+00:00 INFO Az IPN hívás megtörtént.
{"salt":"82qS0PHCQgglSI7Vq90x8pEJjgGHwJrm","orderRef":"etk-5287","method":"CARD","merchant":"SECRET01","finishDate":"2021-07-21T13:21:59+02:00","paymentDate":"2021-07-21T13:21:44+02:00","transactionId":501390091,"status":"FINISHED"} 

Ez oké!

Majd összesen annyit csináltam, hogy a woocommerce beállításokban a devizanemet átállítottam euróra, és ezt követően minden tranzakciót nullás összegűnek kezel és ahogy más esetekben olvastam, a nullásat nem küldi tovább a plugin, hanem megállítja, log:
2021-07-21T11:23:06+00:00 INFO Request is invalid: {"errorCodes":[5014],"salt":"FXrKqSm9E4PSBX3QnZZPcdMYG70CiPhV","merchant":"SECRET02","orderRef":"etk-5290","currency":"EUR","total":0.0}

A simple fiókunkban van eurós és forintos fiók is, mindkettőhöz beírtam a megfelelő credential-t. 
(a merchant id-t módosítottam itt, de a 01-es a forintos fiók, a 02-es végű az eurós fiók)

Kérdésem tehát az, hogy vajon miért lehetnek nullásak az eurós tételek?

Amiket eddig kipróbáltam:

- Bruttóra és nettóra állítottam az adókat
- Kivettem a szállítás opciót
- kivettem a virtuális termék opciót
- kivettem az ezres elválasztót és a tizedesjelet 
- kivettem tizedesjegyek számát 
- kivettem az "Adókulcsok és kalkulációk engedélyezése" opciót 
- A simple fiókban nem látok ehhez releváns beállításokat
- Kikapcsoltam az egyéb plugin-eimet, csak a woocommerce és otp simple plugin maradt bent (illetve az elementor és elementor pro, de enélkül nincs oldal).
- A weboldal sablon csont egyszerű, nincsenek külön woocommerce jellegű funkciók beállítva
- A devizanemet forintra állítva a tranzakciók újra sikeresek

Mit lehetne még kipróbálni? Gondolom ez nem egy plugin hiba, de hátha tud valaki segíteni abban, hogy mit érdemes még kipróbálni, hogy bevegye az eurós fizetést is?

Ha tudnátok valamit javasolni, azt megköszönöm!

- Atti

**Comment by iamgergo** [comment]
Szia!

Kicsekkoláskor az euró végösszeg rendben van?
Vagy ott is van valamilyen elcsúszás?

**Comment by AttiZK** [comment]
Szia,

Igen, forintnál is és eurónál is szépen rendben mutatja a teljes végösszeget a saját pénznemében. Banki átutalásos rendelésnél pedig átvisz gond nélkül a sikeres rendelés oldalra, és a woo rendelések oldalon utána helyesen jelenik meg a rendelés.

**Comment by AttiZK** [comment]
Bármi ötlet, hogy hogyan tudnám egyáltalán debugolni? Mik a tipikus esetek az eurós fizetésnél?

**Comment by iamgergo** [comment]
Sajnos még nem jutottam oda, hogy saját gépen is ellenőrizzem, de eddig ezzel biztosan nem volt gond.

Pontosan hogyan váltasz a két pénznem között?

**Comment by AttiZK** [comment]
Pénznemet a woocommerce általános beállításaiban váltok a főkapcsolóval. Igaz ezelőtt kipróbáltam a "Currency per Product for WooCommerce" plugint, lehet, hogy ez kavart be? Pedig a plugint azóta kikapcsoltam és próbáltam olyan eurós terméket, amit már a kikapcsolás után hoztam létre és elméletileg érintetlen általa.

**Comment by iamgergo** [comment]
Most volt időm tesztelni, és nekem rendben működik minden.

Nem tudom mi kavarhat be. Esetleg érdemes lehet egy friss Woo példányt telepíteni, megnézni hogy úgy megy-e az euró, és ha igen, akkor lépésenként összehasonlítani a már futó áruházzal, hátha ki lehet szűrni, hogy mi a gond.

Sajnos más ötletem nincs.

**Comment by AttiZK** [comment]
Sajnos ez egy működésben lévő webshop nem tudom csakúgy letörölni és újratelepíteni. 

Most azt próbálom meg kideríteni, hogy mi történik az összeggel amíg eljut a plugin-ig. Tudnál abban segíteni, hogy pontosan hol hívja meg a plugin a rendelés összegét?

A PaymentPayload.php ban találtam egy funkciót, amit ehhez a legközelebbinek láttam, a   
"protected static function serialize(WC_Order $order)" funkcióban
a "'total' => $order->get_total()," de ezt hiába módosítottam. 

most a Gateway.php-ban Keresgélek, a process the payment-nél, de elsőre nem egyértelmű.

Azt szeretném kipróbálni, hogy mi van akkor ha a rendelés összegét egy változó helyett beállítom fixen mondjuk 50 euróra. Ezt jó helyen keresem?

**Comment by iamgergo** [comment]
Én egy párhuzamos példányra gondoltam, monjduk egy lokális szerveren, vagy egy aldomainen esetleg.

Most belefutottam egy nagyon hasonló esetbe, de 5014-es hibakód helyett 5013-as kódot dob. Téged hova irányít a kártyás fizetés után? Vissza a checkoutra, vagy a rendelés összegzése oldalra?

**Comment by AttiZK** [comment]
Összerakok akkor egy helyi szervert és azzal próbálkozom tovább. Engem fizetéskor nem irányít sehova, azt az üzenetet dobja, hogy "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra." marad a checkout oldalon és újra megpróbálhatom a rendelést. Eurónál és dollárnál csinálja, tehát a forint kivételével minden más.

**Comment by iamgergo** [comment]
Rendben, akkor jelezd kérlek, hogy mi az eredmény. Nálam forint és euró alapon is rendben megy, nagyon kíváncsi vagyok, hogy mi lehet a gond.

Köszi!

**Comment by AttiZK** [comment]
Én tényleg nem tudom mit csinálok rosszul, most kipróbáltam egy korábbi fázisú helyi szerveren Local-ban, ahol szintén ugyanezzel találkoztam és ezután nem tudtam jobbat, mint egy teljesen friss telepítéssel, alapbeállításokkal, alap wp sablon, mindössze a woo plugin és a simplepay pluginnal kipróbálni. Forinttal működik, euróval nem.

5014-es hibák a 3 különböző host-on:

2021-07-26T15:01:27+00:00 INFO Request is invalid: {"errorCodes":[5014],"salt":"gu9urAc4XoxsRde4eyhowBqcKjs22vCp","merchant":"OMS51794602","orderRef":"wc-13","currency":"EUR","total":0.0}

2021-07-26T15:13:32+00:00 INFO Request is invalid: {"errorCodes":[5014],"salt":"hLUqSQ2ZBOKYRV1E4zZwvvv0oNO092mi","merchant":"OMS51794602","orderRef":"etk-433","currency":"EUR","total":0.0}

2021-07-21T13:46:41+00:00 INFO Request is invalid: {"errorCodes":[5014],"salt":"lbXsvdO4CkUG0ZIuoM1CED5Jqmd24tIq","merchant":"OMS51794602","orderRef":"etk-5302","currency":"EUR","total":0.0}

Forintos fizetésnél pedig szépen kiadja a sikeres log üzenetet:

2021-07-26T15:20:51+00:00 INFO Az IPN hívás megtörtént.
{"salt":"7VEibncdJ8kZuCpTmOp9Q6b5jRPLQHDg","orderRef":"etk-5326","method":"CARD","merchant":"OMS51794601","finishDate":"2021-07-26T17:20:47+02:00","paymentDate":"2021-07-26T17:20:32+02:00","transactionId":501397592,"status":"FINISHED"}


Lehet az, hogy a simple-nél van valami rosszul konfigurálva? Rákérdezek náluk.

**Comment by AttiZK** [comment]
A tárhelyemen nincs bekapcsolva a SOAP modul, ez okozhatja a problémát? Máris kérem a rendszergazdától, hogy kapcsolja be.

**Comment by AttiZK** [comment]
Válasz az OTP-től:

_Kedves Attila!
Az EUR sandbox fiók beállításai valóban hiányosak voltak. Ezt most korrigáltam, kérem próbálja meg újra a fizetést!_

15 órát debugoltam és kiderült, hogy az OTP konfigurálta rosszul! 

Tehét tanulság az 5014-es hibánál, ha legalább az egyik valutával működik, akkor simán lehet, hogy az OTP-nél van a hiba!

Köszi szépen a türelmed és a segítséget, végre tudom használni a plugint! Az app is szuper és ti is!

További jó munkát!
Atti

**Comment by iamgergo** [comment]
Hát sajnos ez már a sokadik eset, hogy rosszul állítják be a fiókokat.

De örülök, hogy megoldódott!
