### ISSUE TITLE
SimplePay tranzakció azonosító a sikeres fizetés utáni levélbe is

### ISSUE THREAD

**Issue by KareszGit** [conedevelopment/simplepay-gateway#79]
- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 5.5.2
- WordPress verzió: 5.8
- PHP verzió: 7.4.21

Sziasztok!

Más rendszereknél a Simple integrációnál az IT csapat szokta tőlem kérni, hogy a vásárlást visszaigazoló levélben is legyen benne a SimplePay tranzakció azonosító. A Sandbox fizetést követően a webshop oldalán ez szuper, hogy ott van, de szinte biztos, hogy bele fognak kötni a levélbe, hogy abban viszont nincs benne.

Van erre valamilyen mezőkódotok amit ha beteszek a visszaigazoló levél kiegészítő szövegéhez, akkor megjeleníti a SimplePay-es tranzakció azonosítót is? Vagy valami egyéb trükk?

A "gyári" WooComm {order_pay_method} mezőben reménykedtem (de sajna ezzel nem jelenik meg semmi), hogy ez jeleníti majd meg azt a hosszú sort ami bekerül a Rendelések közé is, hogy pl.: Fizetési mód: Bankkártya (501402111). Fizetve 2021-07-29 - 17:51. Ügyfél IP: 11.111.11.111  
A fenti sorban csak mintaszámok vannak (nem valós tranz. azonosító vagy IP)

Köszönöm előre is!

**Comment by iamgergo** [comment]
Szia!

Szerintem itt kellene elindulni, hogy ha emailt akarsz módosítani: https://docs.woocommerce.com/document/add-a-custom-field-in-an-order-to-the-emails/

Itt tök egyszerűen ki tudod szedni a transaction ID-t és csak hozzáadod a többi email mezőhöz.
