### ISSUE TITLE
fizetés megtörtént, mégis "visszamondva" státusz

### ISSUE THREAD

**Issue by kukac7** [conedevelopment/simplepay-gateway#80]
hello

par vasarlasnal felmerult egy hiba.

log:
```
2021-07-29T20:05:49+00:00 INFO Az IPN hívás megtörtént.
{"salt":"xy","orderRef":"web-xy","method":"CARD","merchant":"xy","finishDate":"2021-07-29T22:05:24+02:00","paymentDate":"2021-07-29T22:04:33+02:00","transactionId":xy,"status":"FINISHED"}
```

wc admin oldalon igy nez ez ki:

> Ki nem fizetett rendelés visszamondva – időkorlát elérve. Rendelés állapota Fizetés folyamatban volt, majd Visszamondva lett.
> 2021.07.30. - 00:04
> 
> Rendelés állapota Feldolgozás alatt volt, majd Fizetés folyamatban lett.
> 2021.07.29. - 22:06
> 
> Készletszint növekedett: xy
> 2021.07.29. - 22:06
> 
> Rendelés állapota Fizetés folyamatban volt, majd Feldolgozás alatt lett.
> 2021.07.29. - 22:05
> 
> Készletszint csökkent: yx
> 2021.07.29. - 22:05

a gond az, hogy mivel user oldalon lefutott a vasarlas, plusz ki is ment a level a rendelesrol (este 10-kor), azon az oldalon latszolag minden oke.
viszont a mi oldalunkon, visszamondva latszik. ez mitol lehet? mi lehet a gond?
en csak azt nem ertem, miert 2 ora mulva jott a valasz a sikeres fizetesrol?
nem minden simple kartyas rendeles ilyen, de akad par.

koszi a segitseget!

- Simplepay Gateway bővítmény verzió: 2.4.5
- WooCommerce verzió: 4.5.3
- WordPress verzió: 5.5.1
- PHP verzió: 7.2

**Comment by ucsendre** [comment]
Sziasztok!

Ugyanez a jelenség nálunk is előfordul látszólag véletlenszerűen és csak az egyik webshopunk esetében.

- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 5.5.2
- WP sablon: Flatsome, verzió: 3.14.2
- WordPress verzió: 5.8 (hu_HU)
- PHP verzió: 7.4.21

**Comment by iamgergo** [comment]
Nincs 2 óra a két esemény között csak az egyik időbélyeg UTC a másik meg UTC+2, tehát az stimmel.

Ami érdekes az inkább az, hogy a "Rendelés állapota Feldolgozás alatt volt, majd Fizetés folyamatban lett." miért következik be, azután, hogy egyszer ezt már beállította az IPN hívás után. Mert emiatt lesz "Visszamondva" a rendelés 2 óra múlva.

Biztos, hogy a SimplePay bővítmény okozza ezt a jelenséget? Csak azért, mert a bővítményben nincs olyan kód, ami bármilyen állapotról explicit "Fizetés folyamatban" állapotra állítja a rendelést.

@kukac7 @ucsendre Innen én egyenlőre nem nagyon tudok többet tenni azt hiszem, de szerintem érdemes lehet kicsit nyomozni (akár itt), hogy milyen átfedés lehet a két webshop között. Pl.:

- milyen gyakorisággal fodul elő?
- van-e olyan item a rendelésekben, amely mindegyik ilyen esetben ott volt
- készlet bekavarhat-e?
- van-e esetleg átfedés a bővítmények, beállítások között

Köszi!

**Comment by ucsendre** [comment]
Nálunk nagyjából hetente 1-2 alkalommal történik ilyen.
Termékekhez nem köthető és a készlet sem valószínű, hogy befolyásolná (nálunk általában több száz darabos elérhető mennyiségek vannak raktáron).
Vendég és regisztrált vásárló esetében is megtörtént már.
Hónapokkal ezelőtt kezdődött, a php error logban semmi hibára utaló bejegyzés nincs ezekre az időpontokra.
Azóta szinte minden összetevő volt frissítve, mégis időnként megtörténik.
Próbáltuk reprodukálni a jelenséget, de eddig nem sikerült.
@kukac7 ti használjátok a [Nextend Social Login](https://hu.wordpress.org/plugins/nextend-facebook-connect/) bővítményt? Melyik WP sablont használjátok?

**Comment by kukac7** [comment]
@ucsendre mi egy [like-themes](http://like-themes.com/) sablont hasznalunk es az a social login plugin nincs telepitve.

**Comment by powerbuldog** [comment]
A héten nálunk is ugyan ez volt a hiba. A fizetés simple fiókkal történt meg ha ez jelent valamit.

**Comment by jofbe** [comment]
Szia @iamgergo !
Április 9-én és 10-én nálunk is volt 1-1 hasonló eset. A fizetés sikeresen megtörtént, de a WC jegyzeteknél ez volt:

> Készletszint csökkent: xy 79→78
> 
> 2022-04-10 - 23:12 Megjegyzés törlése
> 
> Rendelés állapota Fizetés előtt volt, majd Feldolgozás alatt lett.
> 
> 2022-04-10 - 23:12 Megjegyzés törlése
> 
> Készletszint növekedett: xy 78→79
> 
> 2022-04-10 - 23:12 Megjegyzés törlése
> 
> Rendelés állapota Feldolgozás alatt volt, majd Fizetés előtt lett.
> 
> 2022-04-10 - 23:12 Megjegyzés törlése
> 
> Ki nem fizetett rendelés visszamondva – időkorlát elérve. Rendelés állapota Fizetés előtt volt, majd Visszamondva lett.
> 
> 2022-04-11 - 00:41 Megjegyzés törlése

Mind a két esetben sikeres volt a fizetés, az IPN is jónak tűnik simple oldalán is, és a log-ban is:
`2022-04-10T21:12:23+00:00 INFO Az IPN hívás megtörtént.
{"salt":"xy","orderRef":"wc-5321","method":"CARD","merchant":"xy","finishDate":"2022-04-10T23:12:22+02:00","paymentDate":"2022-04-10T23:11:52+02:00","transactionId":xy,"status":"FINISHED"}`

Simplepay Gateway bővítmény verzió: 2.5.1
WooCommerce verzió: 6.3.1
WordPress verzió: 5.9.3
Sablon: Metro 1.9.3 ([RadiusTheme](https://www.radiustheme.com/))

**Comment by ucsendre** [comment]
szerintem akkor történhet ilyen, ha fizetés után a vásárló a vissza gombra kattint és újratölti a pénztár oldalt - bár ennek nem lenne szabad így működnie....

**Comment by iamgergo** [comment]
Sziasztok!

Ez egy régi issue ugyan, de csak most kaptunk olyan infót az OTP-től ami megvilágította a problémát.

A gond elméletileg az időzóna beállítás lehet. Most frissítettük a bővítményt ennek megfelelően, de hogy rendben működjön be kell állítani a megfelelő időzónát a WP beállításaiban is: https://www.inmotionhosting.com/support/edu/wordpress/change-timezone-2/

Kérlek frissítsétek a bővítményt, és jelezzetek ha továbbra is tapasztaljátok a hibát. 

Köszönjük a türelmet!

**Comment by jofbe** [comment]
@iamgergo Köszönjük szépen a visszajelzést és a javítást, azóta egyelőre nem jött elő a hiba 🎉 😃

**Comment by iamgergo** [comment]
Szuper, reméljük így is marad! :)

**Comment by jofbe** [comment]
@iamgergo , sajnos ez a hiba is megmaradt az oldalunkon. Van, hogy hetekig nem jön elő, és van olyan is, hogy egy bizonyos felhasználónál többször is előfordul.
Az időzóna jól van beállítva.
Lehetséges lenne kivezetni a timeout időt admin felületre, hogy egy nagyobbat tudjunk beállítani, mint 30 perc?

**Comment by iamgergo** [comment]
@jofbe https://github.com/conedevelopment/simplepay-gateway/pull/101

**Comment by jofbe** [comment]
Szuper, köszi!

**Comment by jofbe** [comment]
@iamgergo , a timeout-ot felemeltem másfél órára, de a hiba ugyan úgy fenn áll. Most is egy olyan rendelésnél jött elő, ahol a fizetés egy percen belül sikeresen megtörtént, mégis visszamondva lett a státusz.

**Comment by iamgergo** [comment]
@jofbe Van ötleted, hogy mi okozhatja?
