### ISSUE TITLE
IPN hiba

### ISSUE THREAD

**Issue by gulyaskrisztian** [conedevelopment/simplepay-gateway#81]
- Simplepay Gateway bővítmény verzió: 2.4.14
- WooCommerce verzió: 5.5.2
- WordPress verzió: 5.8
- PHP verzió: 7.4

Először is a bővítmény királyul teszi a dolgát, nem lehet elégszer megköszönni! :)

Egy plugin ütközést fedeztem fel:

Sikeres vásárlás esetén az IPN üzenet nem kerül visszaigazolásra. Átkapcsolatam sandbox módra, plugin ütközés volt a hiba. A WooCommerce Sequential Order Numbers Pro (1.17.0) okozta a hibát. Kikapcsolat bővítmény esetén minden tökéletesen működik. 

Kipróbáltam, hogy nem-e valamilyen karakter okozza, de bármely esetben, ha ez be volt kapcsolva, az alábbi hiba jelentkezett:
Sikeres fizetés esetén a checkout oldalra irányított vissza. A sandboxba bekerült a tranzakció sikeresként, azonban a megrendelés státusza "fizetésre vár"-ba került Woo oldalon, és nem megy ki a megrendelés visszaigazoló email sem. 

Esetleg erre valamilyen megoldás? :)

**Comment by iamgergo** [comment]
Szia!

Köszi, örülünk, hogy használjátok!

Sajnos nem tudunk kompatibilitást biztosítani más bővítményekkel. Így nem tudom, hogy milyen egyszerű megoldás van erre a problémára, de remélem találtok valamit!

**Comment by gulyaskrisztian** [comment]
Szia!

Köszönöm a gyors választ, és hogy foglalkoztatok vele! :)
