### ISSUE TITLE
Parse error: syntax error, unexpected ')' in TwoStepPayment.php on line 74

### ISSUE THREAD

**Issue by mrtamasvarga** [conedevelopment/simplepay-gateway#86]
- Simplepay Gateway bővítmény verzió: 2.5.0
- WooCommerce verzió: 5.3.1
- WordPress verzió: 5.8.1
- PHP verzió: 7.2.30

### Hiba leírása
Frissítés után az alábbi hibát kapjuk:
Parse error: syntax error, unexpected ')' in /web/htdocs3/wp-content/plugins/simplepay-gateway-master/src/TwoStepPayment.php on line 74

**Comment by iamgergo** [comment]
Szia!

Hamarosan megnézem, hogy mi lehet a gond!

**Comment by iamgergo** [comment]
Szerintem PHP 7.2-ben a trailing comma okozhatta a syntax errort. Kiszedtem.
