### ISSUE TITLE
Vissza a kereskedő oldalára  - "Rendelés kifizetése" gomb hiba

### ISSUE THREAD

**Issue by fadrian11** [conedevelopment/simplepay-gateway#87]
- Simplepay Gateway bővítmény verzió: 2.5.1
- WooCommerce verzió: 5.9.0
- WordPress verzió: 5.7.4
- PHP verzió: 7.4

Sziasztok,

Egy problémával találkoztam. 

1. A fizetési oldalon kiválasztom a Simplepay fizetési módot.
2. Az oldalam átdob a Simplepay fizetési oldalra.
3. Itt rákattintok a "Vissza a kereskedő oldalára", vagy épp adok meg egy hibás kártyaadatot(sikertelen kártyaadat). Ekkor a rendszer visszadob a rendelés összesítő oldalra.
4. Ezen a rendelés összesítő oldalon van lehetőség fizetési módot kiválasztani. Nekem a Simplepayt és a banki utalás opciót ajánlja fel. 
5. Kiválasztom a Simplepayt és rákattintok a "Rendelés kifizetése" gombra. Ekkor csak frissül az oldal, de nem történik semmi.

Esetleg ilyenkor vissza kellene irányítani Simplepay fizetési oldalra hogy újból próbálkozzak a fizetéssel?
Esetleg valaki találkozott már hasonló hibával. Mi lehet a módja ha hibásan adták meg a kártya adatokat, és újra próbálkoznának a fizetéssel. Hogy tudnak visszakerülni a fizetési oldalra?

Előre is köszönöm a segítséget.

**Comment by tomRumi** [comment]
hello @fadrian11 , erre talaltal vmi megoldast?

**Comment by ujmeli** [comment]
Sziasztok, sikerült erre megoldást találni, mind náluk a sikertelen fizetések és a "Vissza a kereskedő oldalára" esetén sem jelzi, hogy mi történt, fizetésre vár, majd time out :(.
