### ISSUE TITLE
Tranzakciós üzenet nem jelenik meg hibás / megszakított fizetés esetén

### ISSUE THREAD

**Issue by GrimVanHalter** [conedevelopment/simplepay-gateway#88]
- Simplepay Gateway bővítmény verzió: 2.5.1
- WooCommerce verzió: 6.0.0
- WordPress verzió: 5.8.2
- PHP verzió: 7.4

### Leírás
Sziasztok!

Egy olyan problémát tapasztaltam, hogy a SimplePay (Sandbox) tranzakciós oldalról, ha visszalépek a kereskedői oldalra, a fenti gomb segíségével, vagy megadok egy hibás tranzakcióra futó kártyát, miután visszadob az oldalra semmiféle tájékoztató üzenetet nem jelenít meg az oldalam. 

Ezt talán a legutóbbi wordpress / woocommerce frissítés okozhatja?

Sajnos az üzenet nélül nem tudja elfogadni a SimplePay-es ügyintéző a fizetási mód élesítését

### Reprodukáláshoz szükséges lépések
Weboldal: https://woodestic.eu

1. Termék kosárba rakása
2. átlépés a pénztárba (checkout)
3. adatok megadása
4. SimplePay kiválasztása
5. tetszőlegesen hibás adat kiválasztása, vagy visszalépés a kereskedő oldalára a fenti sorból
6. Nincs megjelenített üzenet

**Comment by robyee05** [comment]
GrimVanHalter sikerült valahogy megoldani a pronblémát? 
Sajnos én is ez miatt várok az élesítésre.

**Comment by GrimVanHalter** [comment]
Üdv,
Igen, ha jól emlékszem akkor vagy pont az otp-nél volt gond a
rendszerükkel, vagy a weboldalunkon futó DIVI témával.
Elnézést a kellemetlenségért.

Ui. Elfelejtettem törölni/lezárni az issue-t?

Robert Mikhel ***@***.***> ezt írta (időpont: 2022. máj. 22.,
V 11:13):

**Comment by robyee05** [comment]
Nem, le volt zárva, én csak szerettem volna valami megoldást találni az én hibámra is ezért érdeklődtem.

**Comment by GrimVanHalter** [comment]
Milyen témát/buildert használsz?

Robert Mikhel ***@***.***> ezt írta (időpont: 2022. máj. 22.,
V 20:06):

**Comment by robyee05** [comment]
Generatepress/ Gutenberg.

**Comment by GrimVanHalter** [comment]
Talán a gutenberg lehet az oka, ha szerencséd van akkor egy frissítéssel
megoldják vagy próbáld meg ha kikapcsolod úgy működik-e.

Robert Mikhel ***@***.***> ezt írta (időpont: 2022. máj. 22.,
V 21:36):
