### ISSUE TITLE
Megszakított fizetésnél nem jelenik meg üzenet

### ISSUE THREAD

**Issue by gmilan88** [conedevelopment/simplepay-gateway#89]
- Simplepay Gateway bővítmény verzió: 2.5.1.
- WooCommerce verzió: 6.3.1.
- WordPress verzió: 5.9.1.
- PHP verzió: 7.4.28.

### Hiba leírása

Sziasztok! 

Ugyanaz a problémám, mint a #88 esetében, de ott válasz nélkül lett lezárva. Sikeres fizetés esetén megjelenik a tranzakciós azonosító és minden egyéb, sikertelennél viszont csak visszadob a checkout oldalra mindenféle infó nélkül.  Lassan minden plugint kikapcsoltam, nincs változás. A shop Divivel épült, ha ez lényeges lehet. Erre valami ötlet?

Köszönöm!

**Comment by iamgergo** [comment]
Szia!

Meg tudod esetleg nézni, hogy az alap Woo témával is fennáll ez a probléma?
Ha nem, akkor valószínűleg a sablonban úszik el valami.

Köszi!

**Comment by PeterEva** [comment]
Sziasztok, nálunk is ez a probléma: "Megszakított-, és Sikertelen fizetés után sajnos továbbra sem kapok vásárlótájékoztató üzenetet, csak ezt a felületet látom mindkét esetben:"
Szintén Divis oldal. Tudtok ebben valami újabb támpontot nyújtani?

Köszönöm!

**Comment by iamgergo** [comment]
Sziasztok!

Utána fogunk nézni, hogy mi lehet a gond, nem tudjuk egyenlőre hogy a bővítményben vagy máshol van a probléma forrása.

Köszi, hogy jeleztétek és a türelmet is!

**Comment by kamanb** [comment]
Sziasztok!
Ugyanebbe a hibába futottam én is. Van erre valamilyen megoldás?
Köszönöm.

**Comment by kamanb** [comment]
Sziasztok,
egy észrevétel ezzel kapcsolatban. A Divi lehetőséget biztosít, hogy manuálisan építsd fel a pénztár oldalt modulonként. (tehát ha nem az alapértelmezett [woocommerce_checkout] shortcode szerepel az oldalon). Úgy vettem észre, hogy ebben az esetben produkálja ezt a hibát.

**Comment by iamgergo** [comment]
Sziasztok!

Futtattunk pár tesztet a legfrissebb verzióval, és nem tapasztaljuk a hibát. Megszakított vagy sikertelen vásárlás esetén is megjelenik az üzenet.

Mi az alap sablonnal dolgozunk, azzal tudunk tesztelni. Egyéb vásárolt, builderes vagy egyedi sablonnál nem tudunk teszteket futtatni, de simán lehet, hogy 1-1 template hiányos, nincsen meghívva valamilyen funkció.

A gond tényleg az egyedi pénztár oldallal lehet, ennek érdemes lehet utánanézni.

Amit esetleg érdemes lehet kipróbálni, az ideiglenesen sablon váltani, és megnézni, hogy ott megfelelően megjelennek-e az üzenetek.

**Comment by medAnnas** [comment]
Does anyone solve this? Thank you

**Comment by ucsendre** [comment]
@medAnnas 

This is not an issue of the plugin.
The problem comes from the wordpress theme used or as stated in previous comments when the checkout page customized.
On one webshop we use The7 theme from themeforest and the default message format of that theme is an automatically disappearing flyout format - which was not acceptable for OTP - so we need to set that to a different format in theme settings.
The plugin works perfectly and does what it is expected about this.
Please check your theme settings and your checkout page.
Kind regards,
Endre
