### ISSUE TITLE
Hiba a fizetés feldolgozásakor

### ISSUE THREAD

**Issue by tomRumi** [conedevelopment/simplepay-gateway#90]
- Simplepay Gateway bővítmény verzió: 2.5.1
- WooCommerce verzió: 6.3.1
- WordPress verzió: 5.9.2
- PHP verzió: 7.4.28

### Hiba leírása
A simple-pay fizetes kivalasztasakor a checkout folyamatban a tovabb gomb egy "Hiba a fizetés feldolgozásakor" hibauzenettel nem lep tovabb. (az atiranyitas nem tortenik meg a simple oldalara)

1. test/sandbox modban megtortenik a redirect es a fizetes sikeres
2. Az IPN helyes: https://webshop.fogaszvilag.hu/?wc-api=wc_gateway_simplepay-gateway 
3. debug modban a naplozas ennyit bejegyzest ir: INFO Request is invalid: {"errorCodes":[5010],"salt":"924OMfWwAOqSWKUQhjU1UucSI4IUgNN5","total":0.0}
4. a simplepaynel a production modban (nem test uzemben) torteno fizetes kozvetlenul sikeres
5. egy sikeres fizetes a simpleben igy nez ki:
 IPN URL https://webshop.fogaszvilag.hu/?wc-api=wc_gateway_simplepay-gateway
Sent IPN hash {"salt":"17P6HcLcVsByldIGaDK2n8q9Wp1VTPkw","orderRef":"101010516482100447510","method":"CARD","merchant":"OMS5290201","refundStatus":"FULL","finishDate":"2022-03-25T13:08:07+01:00","paymentDate":"2022-03-25T13:07:24+01:00","transactionId":253817713,"status":"FINISHED"}
Response status code 200 

a hibas esetben a simplehez nem megy be a request sem

hogyan tudom ezt tovabb debuggolni? WP-ben az osszes plugin deaktivalasa megvolt

halasan koszonom
tom

**Comment by iamgergo** [comment]
Szia!

Igen, valószínűleg a 0.0-val van a gond. Ezt egyébként szűrjük, ingyenes (0.0-ás) terméket át sem ad a SimplePay-nek.

Azt kellene kinyomozni, hogy miért lesz a total 0.0, ha nincs benne ingyenes termék.

Köszi!

**Comment by tomRumi** [comment]
koszonom. megoldodott. vegul a simplepaynel volt a hiba. updateltek a security key length-t es nekunk meg a regi volt. a debug msg felrevezeto volt.
a lenyeg a hiba nem a pluginban volt.
javaslat: alkalomadtan verbose debug msg-k. most a gateway.php-ban ha a $request->send a try catch block miatt barmi hibara fut, vagy nem valid  a valasz  if (! $request->valid()) ugyanazt a hibat adja. lehetetlenseg tudni hogy a $request->send-ben hol volt a gond.

javaslat mar elotte a 
        $request = Request::post(
            Config::url('start'),
            $payload = PaymentPayload::handle($order)

verbose msg-kel ellatasa.. kulonosen az $order definialasanal

legalabbis ez lett volna az en kovetkezo troubleshooting steppem. mivel nem kellett ra sor keruljon, igy nincs mit commitelni

a plugin egyebkent hibatlan. halas koszonet erte!
