### ISSUE TITLE
Plugin telepítési hiba

### ISSUE THREAD

**Issue by robyee05** [conedevelopment/simplepay-gateway#91]
- Simplepay Gateway bővítmény verzió: 0.1.4
- WooCommerce verzió: 6.4.1
- WordPress verzió: 5.8.4
- PHP verzió: 8.0

A plugin telepítésekor az alábbi hiba lép fel, és az oldal összeomlik:
Helyreállítási módban lehet csak visszaállítani. 

Kérem javasoljanak megoldást a problémára. 

2022-05-09T17:24:42+00:00 CRITICAL Uncaught Error: Call to undefined function wc_add_notice() in /home2/repteres/public_html/wp-content/plugins/simplepay/includes/WC_SimplePay_Gateway.php:48
Stack trace:
#0 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_SimplePay_Gateway->__construct()
#1 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#2 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct()
#3 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(890): WC_Payment_Gateways::instance()
#4 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(100): WooCommerce->payment_gateways()
#5 /home2/repteres/public_html/wp-includes/class-wp-hook.php(303): WC_Admin_Menus->settings_page_init()
#6 /home2/repteres/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /home2/repteres/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /home2/repteres/public_html/wp-admin/admin.php(237): do_action()
#9 {main}
  thrown hiba /home2/repteres/public_html/wp-content/plugins/simplepay/includes/WC_SimplePay_Gateway.php fájlban a 48 sorban

**Comment by iamgergo** [comment]
Szia!

A `0.1.4`-es verzió helyett telepítsd a `2.5.1`-es verziót. Szerintem az megoldja a problémát.

Köszi!

**Comment by robyee05** [comment]
Sikerült telepíteni, viszont most az alábbi problémába ütköztem. Esetleg tudnátok javasolni rá megoldást? Nem terméket, hanem szolgáltatást lehet vásárolni. (parkolóhely) Ez már a szolgáltatás kiválasztás, fizetési mód beállítás után, mikor a fizető oldalra irányítana át, akkor dobja fel. 

Hiba: Fatal error: Uncaught Error: Call to a member function get_name() on bool in /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php:140 Stack trace: #0 /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(117): Cone\SimplePay\Payloads\PaymentPayload::mapLineItem() #1 [internal function]: Cone\SimplePay\Payloads\PaymentPayload::Cone\SimplePay\Payloads\{closure}() #2 /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(120): array_reduce() #3 /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(51): Cone\SimplePay\Payloads\PaymentPayload::items() #4 /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(23): Cone\SimplePay\Payloads\PaymentPayload::serialize() #5 /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Gateway.php(140): Cone\SimplePay\Payloads\PaymentPayload::handle() #6 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(439): Cone\SimplePay\Gateway->process_payment() #7 /home2/repteres/public_html/wp-includes/class-wp-hook.php(303): WC_Form_Handler::pay_action() #8 /home2/repteres/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #9 /home2/repteres/public_html/wp-includes/plugin.php(518): WP_Hook->do_action() #10 /home2/repteres/public_html/wp-includes/class-wp.php(763): do_action_ref_array() #11 /home2/repteres/public_html/wp-includes/functions.php(1291): WP->main() #12 /home2/repteres/public_html/wp-blog-header.php(16): wp() #13 /home2/repteres/public_html/index.php(17): require('/home2/repteres...') #14 {main} thrown in /home2/repteres/public_html/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php on line 140

A woocommerce naplóban ez szerepel: 
2022-05-09T17:24:42+00:00 CRITICAL Uncaught Error: Call to undefined function wc_add_notice() in /home2/repteres/public_html/wp-content/plugins/simplepay/includes/WC_SimplePay_Gateway.php:48
Stack trace:
#0 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_SimplePay_Gateway->__construct()
#1 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#2 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct()
#3 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(890): WC_Payment_Gateways::instance()
#4 /home2/repteres/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(100): WooCommerce->payment_gateways()
#5 /home2/repteres/public_html/wp-includes/class-wp-hook.php(303): WC_Admin_Menus->settings_page_init()
#6 /home2/repteres/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /home2/repteres/public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /home2/repteres/public_html/wp-admin/admin.php(237): do_action()
#9 {main}
  thrown hiba /home2/repteres/public_html/wp-content/plugins/simplepay/includes/WC_SimplePay_Gateway.php fájlban a 48 sorban

Köszönöm előre is.

**Comment by iamgergo** [comment]
Nem tudom pontosan, hogy milyen környezetben fut a bővítmény, de a hibanapló több érdekességet is mutat:

- A legfrissebb verzióban nincs `wp-content/plugins/simplepay/includes/WC_SimplePay_Gateway.php` fájl, tehát ha még is ott dobja a hibát, nagyon valószínű, hogy egy sokkal korábbi verzió lett telepítve
- a `wc_add_notice` alap Woo függvény, nem tudom, hogyan lehet undefined. Biztosan a legfrissebb Woo verzió fut?
- A `get_name()` hiba is úgy tűnik, mintha valamilyen régi verzió okozná

Innen sajnos ennyit tudok segíteni.

**Comment by iamgergo** [comment]
Értem, de akkor most pontosan mi a hiba? Köszi!

**Comment by robyee05** [comment]
Kitöltöm a fizetési adatokat kiválasztom a sipmlepay fizetést, és mielőtt átirányítana a fizetési oldalra akkor kapom ezt a hibát. 
Kvázi nem visz át a simplepay fizetésre. Ez még csak sandbox fiók. 


A hiba erre hivatkozik. 
PaymentPayload.php:

131protected static function mapLineItem(WC_Order_Item $item)
132{
133 $product = $item->get_product();
134 $quantity = ceil($item->get_quantity());
135
136 return [
137 ‘tax’ => 0,
138 ‘price’ => ($item->get_total() + $item->get_total_tax()) / $quantity,
139 ‘amount’ => $quantity,
140 ‘title’ => $product->get_name(),
141 ‘description’ => $product->get_description(),
142 ‘ref’ => $product->get_sku() ?: $product->get_id(),
143 ];
144 }

**Comment by iamgergo** [comment]
Ebben a sorban: https://github.com/conedevelopment/simplepay-gateway/blob/master/src/Payloads/PaymentPayload.php#L133, a `$product` változó értéke nem megfelelő. Ezt a kosárban lévő termék egyik függvénye adja, és ezzel most találkozunk először.

Az lehet, hogy valamilyen egyedi bővítményt használtok, ami felülír valamit az alapértelmezett Woo működésben? Mert én úgy ítélem ennyiből, hogy ez nem a SimplePay bővítmény hibája.

**Comment by robyee05** [comment]
Kipróbáltam azt, hogy adtam statikus értékeket az alábbi változóknak:
140 ‘title’ => $product->get_name(),
141 ‘description’ => $product->get_description(),
142 ‘ref’ => $product->get_sku() ?: $product->get_id(),
Ez megoldotta a problémát sikerült fizetést generálni. Valószínűleg az általunk használt bővítmény más függvényeket használ és üres értékeket továbbított a simplepaynek. 
Viszont lenne ezzel kapcsolatban kérdésem. A ‘ref’ változó mit is takar pontosan? 

Továbbá miután működött az oldal sandbox fizetése, elküldtem tesztelésre az OTP-nek. 
Visszakaptam, hogy módosítani kéne a visszatérő oldalak szövegezését, sikertelen fizetés, időtúllépés, megszakított fizetés, valamint sikeres fizetés esetén. (a simplepay küld IPN keresztül)
Ezeket hol tudom módosítani?

**Comment by iamgergo** [comment]
> A ‘ref’ változó mit is takar pontosan?

A termék SKU-ját, vagy ha az nincs, akkor az ID-ját

>  Ezeket hol tudom módosítani?

A fordítási állományokban megtalálhatóak a szövegek, azokat felül tudjátok írni.

**Comment by robyee05** [comment]
Nem arra gondolok, hanem amikor megtörténik a vásárlás a singlepay felületen, utána vissza visz a weboldalra, és ott kiírja, hogy sikeresen megtörtént a vásárlás.
Az OTP kérte, hogy ezen az oldalon jelenjen meg a sikeres tranzakció után a SimplePay tranzakció azonosító: 5xxxxxxxx.
Hogyan tudom ezt megjeleníteni? 

Ugyan úgy mintha egy sikertelen vásárlás után visszadob az oldalra és ott megjelenik a sikertelen üzenet -> ezt megtaláltam a fordítási állományban.

**Comment by robyee05** [comment]
Az alábbi üzenetet kellene módosítanom:
https://nimb.ws/oLMUJt
Ez meg is történt a fordítási állományokban:
https://nimb.ws/3OMJ70

De mégsem változtatja meg.

Illetve sikeres fizetsé után itt kéne megjelenni a Simplepa tranzakciós azonosítónak, de jelenleg nem írja ki. 
https://nimb.ws/Sf5HCk
