### ISSUE TITLE
Translation not working , always show hungary language.

### ISSUE THREAD

**Issue by kevindree** [conedevelopment/simplepay-gateway#92]
- Simplepay Gateway bővítmény verzió: #.#.#
- WooCommerce verzió: #.#.#
- WordPress verzió: #
- PHP verzió: #.#.#

### Hiba leírása
Dear , I am trying to use this plugin , but since we want the admin panel to be in english and chinese , we need to translate this plugin , but unfortunatly we found that the plugin always show hungary translation, now matter which language we are chosen. can you please check and fix this issue ?

**Comment by iamgergo** [comment]
Hello,

Sorry for the late response.

We don't experience this issue. After changing the language of the WP site, the plugin translations are changing as well.

We are using the `get_locale()` function to get the currently set language.
