### ISSUE TITLE
OTP Adattovábbítási Nyilatkozat legördülő menüből nem választható ki.

### ISSUE THREAD

**Issue by Odyn571** [conedevelopment/simplepay-gateway#93]
- Simplepay Gateway bővítmény verzió: #.#.# 1.2.0
- WooCommerce verzió: #.#.# 6.5.1
- WordPress verzió: # 6.0
- PHP verzió: #.#.#

### Hiba leírása

Sziasztok!

Ügyfelem webshopjában a pénztároldalon nem lehet leadni rendelést, ugyanis az OTP Adattovábbítási Nyilatkozat legördülő menüjéből semmit nem lehet kiválasztani. 
![OTP adattovábbítási nyilatkozat](https://user-images.githubusercontent.com/106377762/170671243-070f1165-397d-4179-97ac-f05c761348e4.jpg)

Köszi nagyon a segítséget!

**Comment by ucsendre** [comment]
Az OTP adattovábbítási nyilatkozatot miért kellene külön kiválasztani valami legördülő menüből? Miért nem része az ÁSZF-nek?
Azt a mezőt nem a simplepay gateway plugin illeszti be az oldalba, szóval azt kellene ellenőrizned, hogyan kerül oda.

**Comment by Odyn571** [comment]
Szia!

Az első mondatodra nem tudom a választ, mert nem én készítettem a webshopot, de nagyon köszi, hogy megerősítetted, hogy nem a simplepay gateway plugin a ludas.
