### ISSUE TITLE
Nem lehet rendelést leadni, 0 total-t adna át.

### ISSUE THREAD

**Issue by SFecso** [conedevelopment/simplepay-gateway#94]
- Simplepay Gateway bővítmény verzió: 2.5.1
- WooCommerce verzió: 6.6.1
- WordPress verzió: 6.0
- PHP verzió: 7.4

### Hiba leírása
Nem lehet rendelést leadni, hibaüzenettel leáll. A logban a rendelés összege 0.
![2022-06-30_13-51-51](https://user-images.githubusercontent.com/104104131/176670999-80015d4a-76e1-45cd-a842-840cc6982844.jpg)

**Comment by iamgergo** [comment]
Szia!

Nincs esetleg olyan bővítmény telepítve amely módosítja a rendelés értékét menet közben?

**Comment by iamgergo** [comment]
@SFecso Üdv,

Közben kiderült, hogy akkor ad ilyen hibát a SimplePay, ha a kártyás fizetés nincs engedélyezve a SimplePay fiókban. Ennek módosítását az ügyfélszolgálattól kell kérni.
