### ISSUE TITLE
Fizetés időtúllépés

### ISSUE THREAD

**Issue by theLaszloSzabo** [conedevelopment/simplepay-gateway#96]
- Simplepay Gateway bővítmény verzió: 2.5.1
- WooCommerce verzió: 6.5.1
- WordPress verzió: 6.0
- PHP verzió: 7.2.16-1+0~20190307202415.17+stretch~1.gbpa7be82 (Támogatja a 64bites értékeket)

Sziasztok!

Jelenleg a Sandbox-on keresztül végezzük a fizetési teszteket az élesítés előtt. Az időtúllépés tranzakcióval van annyi gondunk, hogy bármeddig hagyjuk ott a fizetési oldalt még negyed óra múlva is sikeres a fizetés ha rákattintunk a fizetésre.
Az időzónát átállítottuk UTC+2 -re a wordress általános beállításaiban (így szinkronban van a magyar idővel), elvileg onnan szedi a woo is az időzónát. Ennek ellenére nem tudunk timeout tranzakciót produkálni.
Mit hibázhatunk? 

Előre is köszönjük a segítséget.

**Comment by theLaszloSzabo** [comment]
Visszajelzés az SimplePay-től:
"Megvizsgáltam az esetet. Egy saját környezetben én is beállíottam a Conedevelopment bővítményét és megnéztem, hogy milyen adatokat küldd be.
Úgy látom, hogy a bővítmény nem veszi át a WP beállításokban megadott időzónát, ezért működik hibásan a timeout.
Jelezni fogom a bővítmény fejlesztőinek a hibát.
Amennyiben szeretnék tesztelésre beküldeni a rendszerüket, akkor tegyék meg, ezt a hibát nem fogjuk figyelembe venni!"

**Comment by iamgergo** [comment]
Köszi, hogy jelezted, megnézzük!

**Comment by iamgergo** [comment]
Frissítettük a bővítményt, de az oldalon is be kell állítani a megfelelő időzónát: https://www.inmotionhosting.com/support/edu/wordpress/change-timezone-2/

Tudjátok tesztelni frissítés után, jelezzetek ha továbbra sem jó!

Köszi!

**Comment by ucsendre** [comment]
Sziasztok!
Sajnos ez a verzió egyáltalán nem működik nálunk.
A PHP debug logban az alábbi szerepel:
`[03-Sep-2022 15:41:44 UTC] PHP Fatal error:  Uncaught Error: Non-static method Cone\SimplePay\Payloads\PaymentPayload::timeout() cannot be called statically in /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php:37
Stack trace:
#0 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php(24): Cone\SimplePay\Payloads\PaymentPayload::serialize()
#1 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/simplepay-gateway-master/src/Gateway.php(140): Cone\SimplePay\Payloads\PaymentPayload::handle()
#2 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(982): Cone\SimplePay\Gateway->process_payment()
#3 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1206): WC_Checkout->process_order_payment()
#4 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(461): WC_Checkout->process_checkout()
#5 /var/www/vhosts/domain.tld/httpdocs/wp-includes/class-wp-hook.php(307): WC_AJAX::checkout()
#6 /var/www/vhosts/domain.tld/httpdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /var/www/vhosts/domain.tld/httpdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#8 /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action()
#9 /var/www/vhosts/domain.tld/httpdocs/wp-includes/class-wp-hook.php(307): WC_AJAX::do_wc_ajax()
#10 /var/www/vhosts/domain.tld/httpdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#11 /var/www/vhosts/domain.tld/httpdocs/wp-includes/plugin.php(476): WP_Hook->do_action()
#12 /var/www/vhosts/domain.tld/httpdocs/wp-includes/template-loader.php(13): do_action()
#13 /var/www/vhosts/domain.tld/httpdocs/wp-blog-header.php(19): require_once('...')
#14 /var/www/vhosts/domain.tld/httpdocs/index.php(17): require('...')
#15 {main}
  thrown in /var/www/vhosts/domain.tld/httpdocs/wp-content/plugins/simplepay-gateway-master/src/Payloads/PaymentPayload.php on line 37`

WooCommerce verzió:		6.8.2
WordPress verzió:		6.0.2
Nyelv:		hu_HU
Szerver információ:		nginx/1.20.2
PHP verzió:		8.1.9
Az időzóna "Budapest"-re van állítva.

Visszaállítottam a 2.5.1 verziót, az működik.

**Comment by iamgergo** [comment]
A 2.5.3-as verzió rendben van? Ott javítottam a 2.5.2-es hibáját, ha minden igaz.

**Comment by ucsendre** [comment]
Köszönöm a gyors javítást!

**Comment by iamgergo** [comment]
@theLaszloSzabo Az új verzióval rendben megy?

**Comment by theLaszloSzabo** [comment]
Szia Gergő!

Elnézést a lassú válaszért. Frissítettem a legújabb verzióra.
Sajna ugyan úgy nem történik időtúllépés. Bármennyi idő elteltével el tudom indítani a fizetést (egyelőre még csak Sandbox van). Várom az éles rendszerhez az OTP levelét.
Amúgy mennyi idő múlva kéne időtúllépés hibát dobnia? Illetve kéne látni egy számlálót valahol?

Köszi, ha tudtok még segíteni.

**Comment by iamgergo** [comment]
Szia!

> Bármennyi idő elteltével el tudom indítani a fizetést

Ez pontosan hol? a WP checkout oldalon vagy a SimplePay felületén ahol a kártya adatokat adod meg?

**Comment by theLaszloSzabo** [comment]
Szia, a SimplePay oldalán a kártya adatok megadásánál. Már élesre állítottam a fizetést, de korábban a Sandbox-ban szerintem vártam eleget, hogy időtúllépés legyen, de nem történt meg.

Köszi :)

**Comment by iamgergo** [comment]
Értem köszi! Nem tudom mi lehet az oka, most a megfelelő időzónával korrigálva jelenlegi idő + 30 percet ad át a bővítmény a SimlpePay-nek. Ezen túl nem tudunk semmit állítani sajnos.

Köszi a visszajelzést!
