### ISSUE TITLE
IPN válasza túl nagy

### ISSUE THREAD

**Issue by vonanstet** [conedevelopment/simplepay-gateway#98]
- Simplepay Gateway bővítmény verzió: 2.5.1 
- WooCommerce verzió: 6.8.0
- WordPress verzió: 6.0.2
- PHP verzió: 8.0.21 

### Hiba leírása

Sziasztok! 

A sandbox rendszernéljárok, de sajnos nem zárul le rendesen a folyamat. A Simplepay ezt az hibát adja vissza az admin felületén:
IPN válasza túl nagy. A woocommerce adminban fizetés előtt marad a rendelés státusza. 
Van esetleg erre ötlet valakinek?

Az IPN tartalma:

Eredmény IPNTOOBIG Signature NO_SIGNATURE Fogadott válasz pacing--large, 3rem)*-1)!important}.desktop\:ext-mx-0:not([style*=margin]){margin-left:0!important;margin-right:0!important}.desktop\:ext-mx-auto:not([style*=margin]){margin-left:auto!important;margin-right:auto!important}.desktop\:ext-mx-base:not([style*=margin]){margin-left:var(--wp--style--block-gap,1.75rem)!important;margin-right:var(--wp--style--block-gap,1.75rem)!important}.desktop\:ext-mx-lg:not([style*=margin]){margin-left:var(--extendify--spacing--large,3rem)!important;margin-right:var(--extendify--spacing--large,3rem)!important}.desktop\:ext--mx-base:not([style*=margin]){margin-left:calc(var(--wp--style--block-gap, 1.75rem)*-1)!important;margin-right:calc(var(--wp--style--block-gap, 1.75rem)*-1)!important}.desktop\:ext--mx-
...
...
...
"wc-10112..
Index 1 
Időpont 2022.09.05 12:35:49 
IPN URL https://www.---
Elküldött IPN tartalma {"salt":"AptXbJlHsDEYHnxYdqmefwLKHjw0s8CT","orderRef":"wc-10112","method":"CARD","merchant":"OMS53003201","finishDate":"2022-09-05T12:35:40+02:00","paymentDate":"2022-09-05T12:35:24+02:00","transactionId":502130772,"status":"FINISHED"} 
Válasz HTTP kódja 200

**Comment by iamgergo** [comment]
Szia!

Úgy néz ki a WP valamiért egy HTML választ ad vissza. Ennek az oka akár egy bővítmény is lehet, vagy esetleg más beállítás.

Más nem jelzett hasonlóz így gyanítjuk, hogy valamilyen egyedi eset lehet.

**Comment by vonanstet** [comment]
Sajnos elakadtam. Az összes modult kikapcsoltam. Csak a woocommerce és a Simplepay gateway maradt. A sablont is lecseréltem egy alapra. Úgyanaz a hibajelenség. IPN válasza túl nagy...Milyen lehetőségeim vannak még?
Milyen beállítást nézzek meg?

**Comment by ucsendre** [comment]
Szia @vonanstet !
Ellenőrizd a beállításokat a WooCommerce és a SimplePay felületén.
Így kell kinéznie: 
![simplepay](https://user-images.githubusercontent.com/22783189/188468203-281f1624-acb9-49b0-ad17-c94fb740451e.png)

Üdv,
Endre

**Comment by vonanstet** [comment]
> Szia @vonanstet ! Ellenőrizd a beállításokat a WooCommerce és a SimplePay felületén. Így kell kinéznie: ![simplepay](https://user-images.githubusercontent.com/22783189/188468203-281f1624-acb9-49b0-ad17-c94fb740451e.png)
> 
> Üdv, Endre

Nagyon köszönöm a segítséget! Az IPN URL linkjében volt elütés. Most már szépen működik!

Üdv, Gyuri
