### ISSUE TITLE
Simple-ben sikeresen fizetés, WP-ben timeout

### ISSUE THREAD

**Issue by Nieder-hu** [conedevelopment/simplepay-gateway#99]
- Simplepay Gateway bővítmény verzió: 2.5.3
- WooCommerce verzió: 6.8.2
- WordPress verzió: 6.0.2
- PHP verzió: 7.4.30

### Leírás

Sziasztok,

történt egy mindeddig egyszeri, nagyon bosszantó eset. Az ügyfél sikeresen fizetett a Simple-ben, meg is jött az IPN hívás (látom a logban), viszont az order nem kapta vissza ezt, így valamivel később timeoutolt és átment visszamondva státuszba.

Így néz ki a rendelési jegyzetekben:

```
Ki nem fizetett rendelés visszamondva – időkorlát elérve. Rendelés állapota Fizetés előtt volt, majd Visszamondva lett.
2022. 09. 11. - 21:14

Rendelés állapota Feldolgozás alatt volt, majd Fizetés előtt lett.
2022. 09. 11. - 19:56

Rendelés állapota Fizetés előtt volt, majd Feldolgozás alatt lett.
2022. 09. 11. - 19:55
```

Így pedig a logban:

```
2022-09-11T17:55:57+00:00 INFO Az IPN hívás megtörtént.
{"salt":"xxx","orderRef":"wc-8514","method":"CARD","merchant":"xxx","finishDate":"2022-09-11T19:55:53+02:00","paymentDate":"2022-09-11T19:52:32+02:00","transactionId":xxx,"status":"FINISHED"}
```

Érdekes, hogy előtte-utána vannak sikeres fizetések, egyedül ez az egy történt hibásan. Van bármilyen ötletetek, hogy milyen irányba lehet ezzel elindulni?

Köszi!

**Comment by iamgergo** [comment]
Szia!

A WordPress oldalon a megfelelő időzóna (Budapest) van beállítva?

**Comment by Nieder-hu** [comment]
Szia @iamgergo ,

igen, sajnos, Budapest van beállítva, én is ezen a vonalon indultam el az elején.

**Comment by iamgergo** [comment]
Meg tudnád kérdezni az OTP-t, hogy ennél a tranzakciónál mi volt az átadott timeout dátum? Ennél `2022-09-11T19:52:32+02:00` korábbi vagy későbbi?

**Comment by iamgergo** [comment]
Az is lehet, hogy ez valóban a #80 -as issueval hasonló, és amit @ucsendre mondott itt https://github.com/conedevelopment/simplepay-gateway/issues/80#issuecomment-1234272182 az a gond. 

Csak én ezt nem tudom sehogy sem reprodukálni. Azt tapasztalom, hogy ha a thank-you oldalon nyomok egy refresh-t, akkor átvisz a SimplePay oldalára, ahol ezt látom: 

<img width="686" alt="Képernyőfotó 2022-09-16 - 11 25 08" src="https://user-images.githubusercontent.com/6567179/190605046-0cdc60c8-4fc8-4fa5-8371-a113e1510294.png">

De itt akárhova navigálok, nem kavar be a rendelés állapotokba (ettől függetlenül erre rá fogok nézni).

Ki tudjátok próbálni?

1. Rendelés leadása
2. SimplePay fizetés
3. Átirányít a thank-you oldalra
4. IPN megjön -> sikeres fizetés, feldolgozás alatt
5. Visszagomb/újratöltés a thank-you oldalon

Ha valahogy tudnánk ezt reprodukálni, akkor gyorsan meglenne a megoldás is.

Köszi!

**Comment by Nieder-hu** [comment]
Szia,

köszi, nézzük, megpróbáljuk újra előhozni!
